// SRC/JS/alibis.js

export const alibis = {
  medieval: [
    "Vous étiez à la chapelle en prière avec le prêtre.",
    "Vous aidiez la cuisinière à préparer le repas dans les cuisines.",
    "Vous chantiez avec le ménestrel dans la grande salle.",
    "Vous répariez une armure avec le forgeron.",
    "Vous étiez en train de laver du linge avec la lavandière.",
    "Vous discutiez avec le moine dans le scriptorium.",
    "Vous serviez le vin lors du banquet.",
    "Vous montiez la garde avec le sergent d’armes devant la porte.",
    "Vous cueilliez des herbes avec la guérisseuse dans le jardin.",
    "Vous assistiez à la messe avec le châtelain.",
    "Vous racontiez des histoires avec le bouffon dans la cour.",
    "Vous surveilliez les écuries avec l’écuyer.",
    "Vous aidiez la sage-femme auprès d’une future mère.",
    "Vous répariez un tonneau avec le tonnelier.",
    "Vous cousiez dans la chambre avec la couturière.",
    "Vous discutiez discrètement avec la dame de compagnie.",
    "Vous étiez en confession avec le prêtre.",
    "Vous mangiez à la table des domestiques.",
    "Vous étiez au puits avec la fille du meunier.",
    "Vous vendiez des légumes avec la jardinière.",
    "Vous chantiez pour la dame de cœur.",
    "Vous recueilliez des ragots auprès de la tisseuse.",
    "Vous surveilliez les remparts avec l’archer.",
    "Vous aidiez à transporter du bois avec le charpentier.",
    "Vous prépariez le lit de la victime.",
    "Vous faisiez le tour du domaine avec le prévôt.",
    "Vous serviez à la taverne du village.",
    "Vous priiez dans la chapelle avec la nonne.",
    "Vous vous reposiez après la moisson avec le moissonneur.",
    "Vous mangiez dans la cuisine avec le cuisinier.",
    "Vous assistiez à une dispute entre la veuve et le berger.",
    "Vous aidiez la sage-femme à préparer une potion.",
    "Vous tissiez à la lumière des chandelles.",
    "Vous jouiez aux dés avec le jongleur.",
    "Vous aidiez le maître d’armes à entraîner les pages.",
    "Vous soigniez un blessé avec la guérisseuse.",
    "Vous surveilliez la porte avec le garde.",
    "Vous aidiez le messager à préparer une missive.",
    "Vous faisiez la tournée des chambres en tant que servante.",
    "Vous discutiez avec la bâtarde dans l’arrière-cour."
  ],
  renaissance: [
    "Vous posiez pour un tableau dans l’atelier du peintre.",
    "Vous assistiez à une répétition musicale avec le maître de musique.",
    "Vous dîniez avec la duchesse dans ses appartements.",
    "Vous lisiez dans la bibliothèque avec le libraire.",
    "Vous étiez en consultation médicale avec le médecin.",
    "Vous serviez lors d’un banquet avec le maître d’hôtel.",
    "Vous vendiez des tissus avec la tisseuse.",
    "Vous dessiniez des plans avec l’inventeur.",
    "Vous assistiez à une danse avec la danseuse.",
    "Vous discutiez politique avec le cardinal.",
    "Vous décoriez la salle de bal avec la fleuriste.",
    "Vous aidiez à la mise en place d’un bal masqué.",
    "Vous dégustiez un plat avec le chef.",
    "Vous discutiez poésie avec le poète.",
    "Vous cousiez une robe avec la couturière.",
    "Vous étiez en prière avec la sage-femme.",
    "Vous jouiez de la musique avec le musicien.",
    "Vous répariez une serrure avec le serrurier.",
    "Vous vendiez des fleurs au marché.",
    "Vous guidiez des invités dans le palais.",
    "Vous étiez à la messe avec la famille noble.",
    "Vous lisiez une lettre dans la cour intérieure.",
    "Vous aidiez la gouvernante à préparer une réception.",
    "Vous prépariez des pigments pour la peintre.",
    "Vous discutiez avec le jardinier dans l’orangerie.",
    "Vous étiez en train de broder dans la salle des dames.",
    "Vous discutez secret de famille avec la confidente.",
    "Vous dégustiez du vin avec le banquier.",
    "Vous faisiez des emplettes pour la cour.",
    "Vous étiez en réunion avec les marchands.",
    "Vous organisiez une scène de théâtre.",
    "Vous aidiez à ranger les archives du palais.",
    "Vous dansiez à la fête du village.",
    "Vous assistiez à une démonstration scientifique.",
    "Vous étiez en négociation avec des clients étrangers.",
    "Vous prépariez un bal costumé.",
    "Vous organisiez un concert avec le maître de musique.",
    "Vous écriviez des invitations pour la duchesse.",
    "Vous serviez la courtisane dans ses appartements.",
    "Vous étiez en mission pour la médium."
  ],
  victorien: [
    "Vous serviez le thé dans le salon avec la gouvernante.",
    "Vous donniez un cours de piano à la fille du domaine.",
    "Vous promeniez le chien dans le parc avec le jardinier.",
    "Vous lisiez dans la bibliothèque avec la bibliothécaire.",
    "Vous dîniez avec la famille dans la grande salle.",
    "Vous étiez en train de coudre avec la couturière.",
    "Vous aidiez la cuisinière à préparer le pudding.",
    "Vous preniez un bain dans la salle de bains.",
    "Vous assistiez à un bal dans la salle de réception.",
    "Vous discutiez avec le majordome dans l’entrée.",
    "Vous faisiez l’inventaire de la cave à vin.",
    "Vous rangiez les chambres avec la lingère.",
    "Vous conduisiez la calèche avec le cocher.",
    "Vous enseigniez aux enfants avec l’institutrice.",
    "Vous jouiez aux échecs avec le comte.",
    "Vous étiez en train de lire la presse du matin.",
    "Vous faisiez le tour du jardin avec la fleuriste.",
    "Vous aidiez la veuve à ranger ses affaires.",
    "Vous serviez lors d’un dîner mondain.",
    "Vous étiez en train de réparer une horloge.",
    "Vous faisiez la lessive avec la lingère.",
    "Vous serviez le dessert dans la salle à manger.",
    "Vous écoutiez la pianiste jouer.",
    "Vous discutiez discrètement avec la complice.",
    "Vous preniez le thé avec Miss Carter.",
    "Vous écriviez une lettre dans votre chambre.",
    "Vous rangiez la bibliothèque.",
    "Vous prépariez un bouquet pour la maîtresse de maison.",
    "Vous aidiez à la préparation du bal annuel.",
    "Vous étiez au marché avec la cuisinière.",
    "Vous jouiez avec les enfants dans le parc.",
    "Vous faisiez la tournée des chambres.",
    "Vous discutiez avec l’inspecteur dans le bureau.",
    "Vous prépariez le petit-déjeuner.",
    "Vous répariez un livre avec la bibliothécaire.",
    "Vous serviez le café au colonel.",
    "Vous aidiez le jardinier à planter des fleurs.",
    "Vous faisiez la poussière dans le grand salon.",
    "Vous assistiez à une dispute entre le valet et la gouvernante.",
    "Vous serviez un invité inattendu."
  ],
  western: [
    "Vous serviez au bar du saloon avec la barmaid.",
    "Vous jouiez au poker avec les habitués.",
    "Vous répariez une roue de chariot avec le forgeron.",
    "Vous gardiez les vaches avec le cow-boy.",
    "Vous chantiez avec la danseuse sur scène.",
    "Vous prépariez le repas avec la cuisinière.",
    "Vous meniez la diligence à travers la ville.",
    "Vous nettoyiez les tables au saloon.",
    "Vous assistiez à la prière avec le pasteur.",
    "Vous répariez une clôture au ranch.",
    "Vous vendiez des fleurs avec la fleuriste.",
    "Vous aidiez la maîtresse d’école.",
    "Vous soigniez un cheval dans l’écurie.",
    "Vous faisiez la tournée du shérif.",
    "Vous surveilliez le télégraphe au bureau.",
    "Vous étiez en ville pour acheter des provisions.",
    "Vous aidiez à préparer la fête du village.",
    "Vous serviez le bandit recherché au comptoir.",
    "Vous discutiez avec la veuve noire dans la rue.",
    "Vous étiez au marché à vendre du bétail.",
    "Vous faisiez une livraison avec le marchand ambulant.",
    "Vous jouiez de l’harmonica sur le perron du saloon.",
    "Vous assistiez à la messe dans la petite église.",
    "Vous nettoyiez votre arme avec le chasseur de primes.",
    "Vous faisiez la sieste sous le porche.",
    "Vous serviez le shérif à table.",
    "Vous répariez une selle avec le sellier.",
    "Vous brodiez dans la boutique de la dentelière.",
    "Vous étiez à la rivière pour pêcher.",
    "Vous discutiez avec le trappeur au feu de camp.",
    "Vous surveilliez les enfants sur la place.",
    "Vous aidiez la sage-femme lors d’une naissance.",
    "Vous déposiez une lettre au bureau du télégraphe.",
    "Vous faisiez des courses au général store.",
    "Vous preniez un bain au saloon.",
    "Vous prépariez une tarte avec la boulangère.",
    "Vous faisiez la lessive derrière le saloon.",
    "Vous assistiez à un duel en ville.",
    "Vous écoutiez les histoires du vieux prospecteur.",
    "Vous surveilliez le banquet du maire."
  ],
  contemporain: [
    "Vous étiez en réunion Zoom avec des collègues.",
    "Vous dîniez au restaurant avec un(e) ami(e).",
    "Vous faisiez du sport avec la coach sportive.",
    "Vous révisiez un dossier au bureau.",
    "Vous étiez en train de livrer un colis.",
    "Vous gardiez des enfants chez la victime.",
    "Vous étiez en pleine séance photo.",
    "Vous preniez un café avec la fleuriste.",
    "Vous étiez au cinéma avec des amis.",
    "Vous faisiez vos courses au supermarché.",
    "Vous suiviez un cours de yoga.",
    "Vous assistiez à une conférence en ligne.",
    "Vous répariez une fuite chez un client.",
    "Vous faisiez du vélo dans le parc.",
    "Vous étiez en train de cuisiner avec la cheffe.",
    "Vous discutiez dans le hall avec le concierge.",
    "Vous jouiez de la musique dans le métro.",
    "Vous prépariez une commande pour un client.",
    "Vous étiez en réunion à la mairie.",
    "Vous aidiez à la bibliothèque municipale.",
    "Vous étiez en formation professionnelle.",
    "Vous faisiez du bénévolat à l’association.",
    "Vous travailliez tard au bureau.",
    "Vous faisiez une livraison à vélo.",
    "Vous rédigiez un article pour votre blog.",
    "Vous assistiez à une fête de quartier.",
    "Vous preniez un verre avec des collègues.",
    "Vous étiez à la salle de sport.",
    "Vous gardiez le chien d’un voisin.",
    "Vous suiviez un atelier artistique.",
    "Vous faisiez la fermeture du bar.",
    "Vous étiez en intervention chez un client.",
    "Vous faisiez du babysitting chez la victime.",
    "Vous étiez en déplacement professionnel.",
    "Vous prépariez une exposition.",
    "Vous faisiez des achats pour votre boutique.",
    "Vous assistiez à une réunion de copropriété.",
    "Vous étiez en atelier cuisine.",
    "Vous faisiez la tournée des voisins.",
    "Vous suiviez un cours du soir."
  ],
  futuriste: [
    "Vous étiez en maintenance sur le pont du vaisseau.",
    "Vous faisiez une ronde dans le laboratoire avec l’androïde.",
    "Vous assistiez à une réunion holographique.",
    "Vous étiez dans la salle des machines avec le technicien.",
    "Vous meniez une expérience avec le scientifique.",
    "Vous pilotiez un drone de surveillance.",
    "Vous étiez en mission sur une lune voisine.",
    "Vous faisiez une analyse d’ADN dans le labo.",
    "Vous répariez un module de survie.",
    "Vous étiez en formation en réalité augmentée.",
    "Vous testiez un nouveau logiciel IA.",
    "Vous étiez en cryostase supervisée.",
    "Vous assistiez à une réunion du conseil de station.",
    "Vous pilotiez la navette entre deux stations.",
    "Vous faisiez la tournée des serres hydroponiques.",
    "Vous étiez en communication avec la Terre.",
    "Vous répariez un robot défectueux.",
    "Vous participiez à une simulation spatiale.",
    "Vous faisiez une patrouille de sécurité.",
    "Vous étiez en quarantaine médicale.",
    "Vous installiez des capteurs sur la coque.",
    "Vous meniez une négociation avec des aliens.",
    "Vous faisiez une expérience de télépathie.",
    "Vous étiez en inspection avec le commandant.",
    "Vous testiez un nouveau système d’armement.",
    "Vous nettoyiez les panneaux solaires.",
    "Vous faisiez la tournée des quartiers d’équipage.",
    "Vous étiez en entretien psychologique avec l’IA.",
    "Vous répariez une fuite d’oxygène.",
    "Vous faisiez la relève au poste de pilotage.",
    "Vous mettiez à jour la bibliothèque de données.",
    "Vous étiez en exploration virtuelle.",
    "Vous étiez en train de charger du fret interstellaire.",
    "Vous assistiez à une conférence scientifique virtuelle.",
    "Vous faisiez l’inventaire des stocks.",
    "Vous participiez à un test de gravité.",
    "Vous étiez en négociation avec une IA rebelle.",
    "Vous faisiez la maintenance des drones.",
    "Vous étiez en pleine mission de prospection.",
    "Vous répariez une capsule de sauvetage."
  ],
  historique: [
    "Vous assistiez à une réunion du Conseil royal.",
    "Vous étiez en expédition scientifique avec un collègue.",
    "Vous dîniez à la table d’un souverain.",
    "Vous assistiez à un bal impérial.",
    "Vous étiez en train de rédiger un manifeste.",
    "Vous étiez à la bibliothèque nationale.",
    "Vous assistiez à une répétition théâtrale.",
    "Vous participiez à une expérience de laboratoire.",
    "Vous étiez en réunion avec des diplomates étrangers.",
    "Vous donniez un cours à de jeunes élèves.",
    "Vous assistiez à une séance à l’Académie des sciences.",
    "Vous étiez à la messe solennelle avec un cardinal.",
    "Vous visitiez une exposition d’art.",
    "Vous donniez une conférence à l’université.",
    "Vous meniez une enquête policière.",
    "Vous participiez à une séance de l’Assemblée.",
    "Vous étiez en train de peindre dans votre atelier.",
    "Vous assistiez à un procès historique.",
    "Vous étiez en train de corriger un recueil de poèmes.",
    "Vous dîniez chez un ambassadeur.",
    "Vous étiez en voyage diplomatique.",
    "Vous participiez à une répétition musicale.",
    "Vous étiez en train d’écrire des lettres à la cour.",
    "Vous assistiez à une exécution publique.",
    "Vous participiez à un débat dans un salon littéraire.",
    "Vous étiez en observation astronomique.",
    "Vous faisiez une visite guidée d’un monument.",
    "Vous étiez en train de cataloguer des manuscrits.",
    "Vous étiez en promenade avec la reine.",
    "Vous discutiez avec un philosophe au café.",
    "Vous assistiez à une cérémonie officielle.",
    "Vous étiez en train de composer une symphonie.",
    "Vous faisiez la lecture à un enfant royal.",
    "Vous étiez en train de graver une plaque.",
    "Vous faisiez la tournée des salons aristocratiques.",
    "Vous participiez à un banquet d’ambassade.",
    "Vous étiez en réunion secrète avec des conspirateurs.",
    "Vous donniez un spectacle devant la cour.",
    "Vous étiez en train de négocier un traité.",
    "Vous assistiez à l’ouverture d’un parlement."
  ]
};
