// SRC/JS/armes.js

const armesParEpoque = {
  medieval: [
    { nom: "épée longue", genre: "f" },
    { nom: "dague rouillée", genre: "f" },
    { nom: "arbalète", genre: "f" },
    { nom: "arc court", genre: "m" },
    { nom: "masse d'arme", genre: "f" },
    { nom: "gourdin", genre: "m" },
    { nom: "lance", genre: "f" },
    { nom: "hache de guerre", genre: "f" },
    { nom: "poison", genre: "m" },
    { nom: "flèche empoisonnée", genre: "f" },
    { nom: "cordelette", genre: "f" },
    { nom: "pierre sculptée", genre: "f" },
    { nom: "bouclier tranchant", genre: "m" },
    { nom: "pichet de vin empoisonné", genre: "m" },
    { nom: "bâton ferré", genre: "m" },
    { nom: "hachette", genre: "f" },
    { nom: "pique", genre: "f" },
    { nom: "fronde", genre: "f" },
    { nom: "bâton de berger", genre: "m" },
    { nom: "pointe de lance brisée", genre: "f" }
  ],

  victorien: [
    { nom: "chandelier", genre: "m" },
    { nom: "dague ouvragée", genre: "f" },
    { nom: "poison", genre: "m" },
    { nom: "revolver", genre: "m" },
    { nom: "corde", genre: "f" },
    { nom: "coupe-papier", genre: "m" },
    { nom: "tisonnier", genre: "m" },
    { nom: "canne-épée", genre: "f" },
    { nom: "coussin", genre: "m" },
    { nom: "fiole d'acide", genre: "f" },
    { nom: "couteau de cuisine", genre: "m" },
    { nom: "sabre d'apparat", genre: "m" },
    { nom: "flacon de chloroforme", genre: "m" },
    { nom: "ombrelle piquante", genre: "f" },
    { nom: "statue lourde", genre: "f" },
    { nom: "pic à glace", genre: "m" },
    { nom: "fil de soie", genre: "m" },
    { nom: "pied de biche", genre: "m" },
    { nom: "boîte à musique piégée", genre: "f" },
    { nom: "épingle à chapeau", genre: "f" }
  ],

  futuriste: [
    { nom: "laser", genre: "m" },
    { nom: "nano-virus", genre: "m" },
    { nom: "scalpel énergisé", genre: "m" },
    { nom: "module saboté", genre: "m" },
    { nom: "drone d’entretien", genre: "m" },
    { nom: "câble à haute tension", genre: "m" },
    { nom: "seringue de protoxyde", genre: "f" },
    { nom: "capsule toxique", genre: "f" },
    { nom: "sabre plasma", genre: "m" },
    { nom: "rayon ionique", genre: "m" },
    { nom: "gants exosquelette", genre: "m" },
    { nom: "champ de force", genre: "m" },
    { nom: "pulvérisateur neurotoxique", genre: "m" },
    { nom: "injecteur d'ADN", genre: "m" },
    { nom: "grenade EMP", genre: "f" },
    { nom: "micro-drone de combat", genre: "m" },
    { nom: "clé quantique", genre: "f" },
    { nom: "bâton gravitationnel", genre: "m" },
    { nom: "pistolet à impulsion", genre: "m" },
    { nom: "puce corrompue", genre: "f" }
  ],

  contemporain: [
    { nom: "couteau de cuisine", genre: "m" },
    { nom: "pistolet", genre: "m" },
    { nom: "batte de baseball", genre: "f" },
    { nom: "ciseau de bureau", genre: "m" },
    { nom: "câble électrique", genre: "m" },
    { nom: "poison", genre: "m" },
    { nom: "seringue", genre: "f" },
    { nom: "voiture", genre: "f" },
    { nom: "casserole", genre: "f" },
    { nom: "tournevis", genre: "m" },
    { nom: "marteau", genre: "m" },
    { nom: "bouteille cassée", genre: "f" },
    { nom: "extincteur", genre: "m" },
    { nom: "corde à linge", genre: "f" },
    { nom: "statue décorative", genre: "f" },
    { nom: "ordinateur piégé", genre: "m" },
    { nom: "statuette", genre: "f" },
    { nom: "roulette à pizza", genre: "f" },
    { nom: "lampe lourde", genre: "f" },
    { nom: "trophée sportif", genre: "m" }
  ],

  western: [
    { nom: "colt", genre: "m" },
    { nom: "lasso", genre: "m" },
    { nom: "carabine", genre: "f" },
    { nom: "hachette", genre: "f" },
    { nom: "couteau de trappeur", genre: "m" },
    { nom: "bouteille de whisky cassée", genre: "f" },
    { nom: "pelle", genre: "f" },
    { nom: "pioche", genre: "f" },
    { nom: "corde", genre: "f" },
    { nom: "poison", genre: "m" },
    { nom: "banjo", genre: "m" },
    { nom: "roue de chariot", genre: "f" },
    { nom: "tisonnier de cheminée", genre: "m" },
    { nom: "mors de cheval", genre: "m" },
    { nom: "coup de sabot", genre: "m" },
    { nom: "pistolet à poudre noire", genre: "m" },
    { nom: "fourche", genre: "f" },
    { nom: "barre de fer", genre: "f" },
    { nom: "pierre ramassée", genre: "f" },
    { nom: "gourdin de saloon", genre: "m" }
  ],

  renaissance: [
    { nom: "épée de cour", genre: "f" },
    { nom: "poignard", genre: "m" },
    { nom: "arbalète de chasse", genre: "f" },
    { nom: "pistolet à rouet", genre: "m" },
    { nom: "fiole de poison", genre: "f" },
    { nom: "canne sculptée", genre: "f" },
    { nom: "coup de statue", genre: "m" },
    { nom: "couteau de cuisine", genre: "m" },
    { nom: "cordon de soie", genre: "m" },
    { nom: "pichet de vin lourd", genre: "m" },
    { nom: "arc d'apparat", genre: "m" },
    { nom: "flèche empoisonnée", genre: "f" },
    { nom: "bâton d'alchimiste", genre: "m" },
    { nom: "pierre précieuse", genre: "f" },
    { nom: "poudre noire", genre: "f" },
    { nom: "essuie de cuisine", genre: "m" },
    { nom: "boucle de ceinture", genre: "f" },
    { nom: "coup de candélabre", genre: "m" },
    { nom: "statue d'ange", genre: "f" },
    { nom: "pied de table", genre: "m" }
  ],

  historique: [
    { nom: "gladius romain", genre: "m" },
    { nom: "hache viking", genre: "f" },
    { nom: "lance grecque", genre: "f" },
    { nom: "arc composite", genre: "m" },
    { nom: "sarbacane", genre: "f" },
    { nom: "épée d’apparat", genre: "f" },
    { nom: "poison antique", genre: "m" },
    { nom: "pique de hallebardier", genre: "f" },
    { nom: "bouclier spartiate", genre: "m" },
    { nom: "fronde biblique", genre: "f" },
    { nom: "massue de chef gaulois", genre: "f" },
    { nom: "pierre taillée", genre: "f" },
    { nom: "filet de gladiateur", genre: "m" },
    { nom: "dard empoisonné", genre: "m" },
    { nom: "coup de sceptre royal", genre: "m" },
    { nom: "sabre napoléonien", genre: "m" },
    { nom: "parchemin toxique", genre: "m" },
    { nom: "trident", genre: "m" },
    { nom: "javelot", genre: "m" },
    { nom: "pointe de lance", genre: "f" }
  ]
};

export { armesParEpoque };
