// SRC/JS/armeActions.js

const armeActions = {
  // TRANCHANT/POINTU
  "couteau": ["poignardé", "égorgé", "entaille mortelle"],
  "couteau de cuisine": ["poignardé", "égorgé", "entaille profonde"],
  "dague rouillée": ["poignardé", "entaille mortelle"],
  "épée longue": ["poignardé", "transpercé", "décapité"],
  "hache de guerre": ["décapité", "coupé en deux", "mutilé"],
  "canne-épée": ["poignardé", "transpercé"],
  "fourche": ["transpercé", "empalé"],
  "couteau de récolte": ["poignardé", "entaille profonde"],
  "broche à viande": ["transpercé", "empalé"],
  "flèche empoisonnée": ["transpercé par une flèche", "empoisonné"],
  "arc court": ["transpercé par une flèche", "flèche dans le cœur"],
  "arbalète": ["transpercé par un carreau", "carreau dans la gorge"],
  "sécateur": ["entaillé", "sectionné"],
  "ciseau à bois": ["poignardé", "entaillé"],
  "ciseaux": ["entaillé", "égorgé"],
  "scalpel": ["entaillé", "égorgé"],
  "scalpel énergisé": ["entaillé", "découpé"],
  "bistouri": ["entaillé", "égorgé"],
  "rasoir": ["égorgé"],
  "tournevis": ["poignardé", "perforé"],
  "clé": ["poignardé (clé pointue)", "étranglé (cordon de clé)"],
  "clé à molette": ["crâne fracassé", "assommé"],

  // CONTONDANT/FRAPPANT
  "masse d'arme": ["crâne fracassé", "écrasé"],
  "marteau": ["crâne fracassé", "écrasé"],
  "marteau à viande": ["crâne fracassé"],
  "tisonnier": ["crâne fracassé", "brûlé"],
  "pied de biche": ["crâne fracassé", "broyé"],
  "barre de fer": ["crâne fracassé", "broyé"],
  "bâton ferré": ["crâne fracassé", "battu à mort"],
  "bâton gravitationnel": ["écrasé", "projeté dans le vide"],
  "bâton de berger": ["crâne fracassé", "battu à mort"],
  "bâton": ["crâne fracassé", "battu à mort", "empalé"],
  "gourdin": ["crâne fracassé", "battu à mort"],
  "tabouret": ["crâne fracassé", "assommé"],
  "pelle": ["crâne fracassé", "assommé"],
  "pioche": ["crâne percé", "transpercé"],
  "rame": ["crâne fracassé", "assommé"],
  "planche": ["crâne fracassé", "assommé"],
  "coupelle": ["crâne fracassé", "assommé"],
  "brique": ["crâne fracassé"],
  "pot de fleur": ["crâne fracassé", "assommé"],
  "statue lourde": ["écrasé", "crâne fracassé"],
  "statue d'ange": ["écrasé", "crâne fracassé"],
  "statue": ["écrasé", "crâne fracassé"],
  "buste": ["crâne fracassé", "assommé"],
  "pied de chaise": ["crâne fracassé", "assommé"],
  "pied de télescope": ["crâne fracassé"],
  "pied de lampe": ["crâne fracassé", "assommé"],
  "balai": ["crâne fracassé", "battu à mort"],
  "tenailles": ["broyé", "étranglé"],
  "seau": ["assommé", "crâne fracassé"],
  "pierre sculptée": ["crâne fracassé", "lapidé"],
  "pierre": ["crâne fracassé", "lapidé"],
  "caillou": ["crâne fracassé"],
  "livre": ["crâne fracassé", "étouffé (livre épais sur le visage)"],
  "ordinateur portable": ["crâne fracassé"],
  "pot de peinture": ["assommé"],
  "casserole": ["crâne fracassé", "assommé"],
  "poêle": ["crâne fracassé", "brûlé"],
  "lampe": ["crâne fracassé", "électrocuté"],
  "lampe UV": ["brûlé", "électrocuté"],
  "arrosoir": ["assommé"],
  "seau de poix": ["brûlé vif"],
  "pot en terre": ["crâne fracassé"],
  "houlette": ["crâne fracassé"],
  "fer à cheval": ["crâne fracassé"],
  "balance": ["crâne fracassé"],
  "presse-papier": ["crâne fracassé"],
  "rame": ["crâne fracassé", "assommé"],
  "valise": ["crâne fracassé", "étouffé"],
  "caisse": ["crâne fracassé", "écrasé"],
  "boîte": ["crâne fracassé", "écrasé"],
  "boîte lourde": ["écrasé", "crâne fracassé"],

  // ÉTRANGLEMENT, ASPHYXIE, NOYADES
  "cordelette": ["étranglé"],
  "corde": ["pendu", "étranglé"],
  "ceinture": ["étranglé"],
  "chaîne": ["étranglé", "battu à mort"],
  "torchon": ["étouffé"],
  "coussin": ["étouffé"],
  "sac poubelle": ["étouffé"],
  "lacet": ["étranglé"],
  "filet": ["étranglé", "étouffé"],
  "ruban": ["étranglé"],
  "cravate": ["étranglé"],
  "casque audio": ["étranglé (avec le câble)"],
  "souris": ["étranglé (câble)"],
  "poulie": ["étranglé"],

  // TIR, BALLES, FLÈCHES
  "revolver": ["abattu", "blessure mortelle par balle"],
  "colt": ["abattu", "blessure mortelle par balle"],
  "carabine": ["abattu", "blessure mortelle par balle"],
  "pistolet": ["abattu", "blessure mortelle par balle"],
  "pistolet à impulsion": ["électrocuté", "grillé sur place"],
  "arc": ["transpercé par une flèche", "flèche dans le cœur"],
  "canon": ["détruit", "explosé"],
  "bâton gravitationnel": ["écrasé", "projeté dans le vide"],

  // EMPOISONNEMENT, CHIMIQUE
  "pichet de vin empoisonné": ["empoisonné"],
  "bouteille de lessive": ["empoisonné"],
  "seringue": ["empoisonné", "injection létale"],
  "seringue de protoxyde": ["empoisonné", "injection létale"],
  "flacon de poison": ["empoisonné"],
  "injecteur d'ADN": ["empoisonné", "injection létale"],
  "bouteille d'eau": ["empoisonné (si eau trafiquée)"],
  "pot de farine": ["étouffé (avaler ou respirer)", "empoisonné (si farine trafiquée)"],

  // OBJETS DÉTOURNÉS
  "bouteille": [
    "empoisonné (si contenu toxique)",
    "crâne fracassé",
    "égorgé (si brisée)"
  ],
  "bouteille cassée": ["égorgé", "entaillé"],
  "verre": ["entaillé", "égorgé (si brisé)"],
  "chaise": ["crâne fracassé", "étouffé"],
  "magazine": ["étouffé (roulé et enfoncé dans la gorge)"],
  "planche à découper": ["crâne fracassé"],
  "tour PC": ["crâne fracassé"],
  "tablette électronique": ["crâne fracassé"],
  "casque VR": ["étouffé", "crâne fracassé"],
  "pied de micro": ["transpercé", "perforé"],
  "buste": ["crâne fracassé", "assommé"],
  "rame": ["crâne fracassé", "assommé"],
  "livre sacré": ["crâne fracassé"],
  "loupe": ["brûlé (concentré par le soleil)"],

  // FUTURISTE/ÉLECTRIQUE
  "clé quantique": ["électrocuté", "désintégré"],
  "clé de commande": ["électrocuté"],
  "câble électrique": ["électrocuté", "étranglé"],
  "câble à haute tension": ["électrocuté", "brûlé"],
  "batterie": ["électrocuté", "explosé"],
  "extincteur": ["crâne fracassé", "asphyxié (poudre)"],
  "panneau de signalisation": ["crâne fracassé"],
  "tube cryo": ["gelé à mort", "crâne fracassé"],

  // SPÉCIFIQUES HISTORIQUE/RENAISSANCE
  "statue d’Empereur": ["écrasé", "crâne fracassé"],
  "statue de dieu": ["écrasé", "crâne fracassé"],
  "croix": ["crâne fracassé", "empalé"],
  "banc": ["crâne fracassé"],
  "mortier": ["crâne fracassé"],
  "chandelier": ["crâne fracassé", "assommé", "étouffé"],
  "rame": ["crâne fracassé", "assommé"],
  "cage": ["crâne fracassé"],

  // AUTRES/ACCIDENT
  "sac de grain": ["étouffé"],
  "sac de pièces": ["crâne fracassé"],
  "pierre précieuse": ["crâne fracassé"],
  "statue d'ange": ["écrasé", "crâne fracassé"],
  "crâne": ["crâne fracassé"],
  "crochet": ["empalé", "accroché"],
  "houlette": ["crâne fracassé"],
  "bâton d'alchimiste": ["crâne fracassé", "battu à mort"],
  "livre de comptes": ["crâne fracassé"],

  // OBJETS DE LUXE
  "carafe": ["crâne fracassé"],
  "assiette": ["crâne fracassé"],
  "coupelle": ["crâne fracassé"],
  "caisse": ["crâne fracassé", "écrasé"],
  "boîte": ["crâne fracassé", "écrasé"],

  // PIÈGES ET DIVERS
  "piège à ours": ["morsure fatale", "sectionné"],
  "piège": ["sectionné", "déchiqueté"],

  // SI ABSENT DU MAPPING
  // "autre": ["tué"]
};

export { armeActions };
