export const indices = {
  medieval: [
    "Un morceau de tissu arraché trouvé près du lieu du crime.",
    "Une dague gravée oubliée dans la salle.",
    "Des traces de boue menant à la chambre de la victime.",
    "Un bijou appartenant à un(e) suspect(e) retrouvé sur place.",
    "Un gobelet de vin renversé contenant une étrange poudre.",
    "Un parchemin déchiré portant une menace.",
    "Un témoin affirme avoir entendu une dispute la veille.",
    "Des empreintes de pas dans la boue sous la fenêtre.",
    "Un mouchoir brodé de lettres mystérieuses.",
    "Un animal du domaine retrouvé blessé près du château.",
    "Un coffre forcé dans les appartements de la victime.",
    "La clé de la tour retrouvée dans le jardin.",
    "Un morceau de corde usée sous le lit.",
    "Un livre de prières ouvert à une page sur la trahison.",
    "Des cendres récentes dans la cheminée.",
    "Une bague avec un blason inconnu.",
    "Des herbes médicinales dispersées dans la chambre.",
    "Un message codé trouvé dans la cuisine.",
    "Un cri entendu au milieu de la nuit.",
    "Un tissu imbibé d’un liquide suspect.",
    "Une chaussure perdue dans la cour.",
    "Un plan du château griffonné à la hâte.",
    "Une pièce étrangère trouvée dans la main de la victime.",
    "Un parfum inhabituel flotte dans la pièce.",
    "Une porte secrète entrouverte.",
    "Un morceau de pain empoisonné.",
    "Une lettre d’amour cachée dans un coussin.",
    "Des traces de sang menant aux écuries.",
    "Des plumes sur le sol près du corps.",
    "Un chandelier renversé.",
    "Un seau d’eau versé dans la salle juste avant le drame.",
    "Un arc caché dans la remise.",
    "Une cape mouillée retrouvée dans la cuisine.",
    "Un bracelet cassé sous la table.",
    "Un témoin a vu quelqu’un courir vers la chapelle.",
    "Des mouches attirées par un liquide répandu.",
    "Une empreinte de botte inhabituelle.",
    "Des morceaux de cire sous le lit.",
    "Un anneau glissé dans une chaussure.",
    "Un message à demi effacé sur le mur."
  ],
  renaissance: [
    "Un gant brodé retrouvé dans l’atelier du peintre.",
    "Un flacon d’encre renversé sur une lettre inachevée.",
    "Des traces de pas menant à la bibliothèque.",
    "Une épingle à cheveux dorée trouvée sous le fauteuil du duc.",
    "Un parfum rare flotte dans l’air du salon.",
    "Un morceau de partition brûlé dans la cheminée.",
    "Un mouchoir taché de vin retrouvé dans la salle de bal.",
    "Un carnet de croquis déchiré.",
    "Un bijou de cour manquant à l’appel.",
    "Une clef cachée derrière un tableau.",
    "Un parchemin scellé dans une doublure de vêtement.",
    "Un témoin a vu un(e) suspect(e) rôder la nuit.",
    "Une perle roulée sous une table.",
    "Des cendres d’une lettre brûlée.",
    "Un médaillon contenant un portrait secret.",
    "Une chaussure boueuse retrouvée sur un tapis précieux.",
    "Une fiole vide d’un poison rare.",
    "Un plan de la ville annoté en secret.",
    "Un pétale de fleur écrasé sur le rebord d’une fenêtre.",
    "Une bague portant la devise d’un clan rival.",
    "Des traces de cire sur un parchemin.",
    "Un livre de comptes manquant.",
    "Un éventail cassé dans le jardin.",
    "Un bout de ruban déchiré.",
    "Une feuille de musique annotée.",
    "Un billet doux glissé dans un livre.",
    "Un pinceau taché de sang.",
    "Des traces de pas sur le carrelage.",
    "Un manteau oublié dans une ruelle.",
    "Un mouchoir brodé d’initiales inconnues.",
    "Un peigne d’ivoire fendu.",
    "Un bouquet fané dans les appartements de la victime.",
    "Des éclats de verre sous un meuble.",
    "Un témoin affirme avoir entendu une voix étrangère.",
    "Un secret griffonné sur la nappe.",
    "Un coffre entrouvert dans la chambre.",
    "Un message codé dissimulé dans une reliure.",
    "Un parfum étranger sur un coussin.",
    "Un morceau de masque de bal déchiré.",
    "Une clé de coffre-fort disparue."
  ],
  victorien: [
    "Un gant de dame retrouvé dans le jardin.",
    "Une montre à gousset arrêtée à l’heure du crime.",
    "Une lettre anonyme sur le bureau de la victime.",
    "Un foulard parfumé caché sous le lit.",
    "Des traces de boue sur le tapis du salon.",
    "Un verre de liqueur renversé dans la bibliothèque.",
    "Un mouchoir brodé d’initiales suspectes.",
    "Un carnet d’adresses ouvert à un nom en particulier.",
    "Une silhouette vue à la fenêtre par la gouvernante.",
    "Une boucle d’oreille oubliée dans le divan.",
    "Des empreintes de pas dans la serre.",
    "Un fragment de miroir brisé dans la chambre.",
    "Un bouton de manchette sous le fauteuil.",
    "Des traces de pas mouillés dans le vestibule.",
    "Une clé manquante au trousseau du majordome.",
    "Un billet de train non utilisé.",
    "Un livre d’herboristerie annoté.",
    "Un flacon vide d’opium.",
    "Un message griffonné sur un coin de nappe.",
    "Un peigne d’argent cassé.",
    "Une photo déchirée.",
    "Des pétales de rose sur le rebord de la fenêtre.",
    "Un chapeau oublié dans le hall.",
    "Un ticket de théâtre dans la poche d’une veste.",
    "Des cendres dans la cheminée du bureau.",
    "Un stylo cassé près du cadavre.",
    "Un parfum inconnu sur un mouchoir.",
    "Un pansement ensanglanté trouvé dans la corbeille.",
    "Un reçu bancaire brûlé à moitié.",
    "Des plumes noires sur le balcon.",
    "Une lettre de chantage cachée sous un tapis.",
    "Un éclat de verre dans la salle à manger.",
    "Un agenda déchiré.",
    "Des gants d’homme dans la chambre de la victime.",
    "Un verre à vin brisé retrouvé dans le parc.",
    "Une trace de rouge à lèvres sur une tasse.",
    "Un morceau de soie près de la fenêtre.",
    "Un bouton arraché de la veste d’un suspect.",
    "Des empreintes de bottes dans la boue.",
    "Un carnet de dettes disparu."
  ],
  western: [
    "Un colt encore chaud trouvé derrière le saloon.",
    "Des traces de bottes menant à l’écurie.",
    "Un foulard ensanglanté retrouvé près du puits.",
    "Un as de pique glissé sous la porte.",
    "Des pièces d’or tombées le long de la route.",
    "Un mouchoir brodé dans la poche d’un suspect.",
    "Un témoin a entendu un coup de feu la veille.",
    "Une cartouche vide dans la chambre.",
    "Un sombrero oublié sur la clôture.",
    "Des traces de pas menant au ranch.",
    "Un message gravé sur la porte du saloon.",
    "Un éperon cassé retrouvé sous le porche.",
    "Un cheval sellé abandonné près de la rivière.",
    "Une bouteille de whisky vide sous le lit.",
    "Un bandana imbibé de sueur retrouvé dans la grange.",
    "Un morceau de corde effilochée.",
    "Un gant de cuir perdu dans la ruelle.",
    "Un éclat de miroir sur la piste.",
    "Des graines de tabac répandues sur le sol.",
    "Un chapeau troué accroché à un clou.",
    "Une lettre froissée dans la poche d’un pantalon.",
    "Un mouchoir taché de poudre noire.",
    "Une étoile de shérif abîmée.",
    "Un billet de banque déchiré.",
    "Une flasque gravée.",
    "Une trace de sang sur la selle d’un cheval.",
    "Un bouton de chemise arraché.",
    "Un cigare à moitié consumé.",
    "Un éclat de verre dans l’abreuvoir.",
    "Un morceau de carte au trésor.",
    "Un témoin a vu un cavalier partir au galop.",
    "Une boucle de ceinture dorée retrouvée dans la poussière.",
    "Un journal intime caché dans une botte.",
    "Un éperon brisé dans la grange.",
    "Un foulard parfumé dans la poche d’une veste.",
    "Une bouteille de remède vide.",
    "Une lettre signée d’un mystérieux “X”.",
    "Un collier de perles cassé.",
    "Des traces de pas menant au cimetière.",
    "Un gant d’enfant retrouvé sur la scène du crime."
  ],
  contemporain: [
    "Un téléphone portable oublié sur les lieux du crime.",
    "Un ticket de métro retrouvé près du corps.",
    "Une empreinte digitale sur un verre.",
    "Un badge d’accès oublié dans un ascenseur.",
    "Une clé USB contenant des fichiers suspects.",
    "Un message vocal menaçant sur le répondeur.",
    "Un reçu de paiement dans une poche.",
    "Des résidus de poudre blanche sur une étagère.",
    "Un agenda ouvert à la date du drame.",
    "Une photo compromettante sur un smartphone.",
    "Une trace de rouge à lèvres sur une chemise.",
    "Un ticket de caisse d’un commerce voisin.",
    "Un e-mail supprimé mais retrouvé dans la corbeille.",
    "Un badge d’identité non attribué.",
    "Un chewing-gum mâché collé sous la table.",
    "Des traces de pas humides dans le couloir.",
    "Un mot griffonné sur un post-it.",
    "Une clé cassée dans la serrure.",
    "Un morceau de tissu arraché dans la cage d’escalier.",
    "Une boîte de médicaments vide.",
    "Un ticket de cinéma du soir du crime.",
    "Un stylo publicitaire d’une société concurrente.",
    "Un reçu de livraison oublié.",
    "Des images de vidéosurveillance effacées.",
    "Un double des clés retrouvé sous un paillasson.",
    "Une carte de fidélité d’un club privé.",
    "Un extrait de conversation WhatsApp.",
    "Des traces de peinture sur les chaussures.",
    "Un badge de parking oublié.",
    "Un plan d’accès griffonné.",
    "Une carte bancaire oubliée.",
    "Un courrier anonyme dans la boîte aux lettres.",
    "Une trace de pneu inhabituelle.",
    "Un gobelet de café renversé.",
    "Un carnet d’adresses déchiré.",
    "Des empreintes de pas dans la terre fraîche.",
    "Un ticket de restaurant.",
    "Un badge d’accès à la salle informatique.",
    "Un morceau de ruban adhésif.",
    "Des traces de sang sur la poignée de porte."
  ],
  futuriste: [
    "Un implant électronique désactivé retrouvé sur la scène.",
    "Des traces de nano-robots dans le système de ventilation.",
    "Une carte d’accès biométrique usurpée.",
    "Un rapport d’IA effacé mystérieusement.",
    "Une empreinte digitale falsifiée.",
    "Un hologramme brouillé enregistré avant le crime.",
    "Un résidu de liquide cryogénique.",
    "Un drone de surveillance retrouvé endommagé.",
    "Un message codé sur un terminal informatique.",
    "Une capsule de médicaments vides.",
    "Un circuit imprimé brûlé.",
    "Des logs système supprimés.",
    "Un badge d’accès à un secteur interdit.",
    "Un microprocesseur manquant sur le robot assistant.",
    "Des traces d’ADN modifié.",
    "Un script informatique en cours d’exécution.",
    "Une signature énergétique inconnue.",
    "Un gant de manipulation robotique.",
    "Un fragment de puce mémoire.",
    "Un plan de la station annoté à la main.",
    "Une clé d’accès universelle retrouvée sur un suspect.",
    "Un message subliminal intercepté.",
    "Des traces de pas dans le sas d’air.",
    "Un échantillon de sol extraterrestre.",
    "Un journal de bord effacé.",
    "Un casque de réalité augmentée fissuré.",
    "Un bracelet d’identification arraché.",
    "Des résidus de carburant sur le sol.",
    "Un tube de nano-médicament vide.",
    "Un micro drone retrouvé sous un siège.",
    "Un module de communication piraté.",
    "Une empreinte énergétique sur la console.",
    "Un badge de maintenance non autorisé.",
    "Un message audio crypté.",
    "Un gant de manipulation atomique.",
    "Un rapport de maintenance falsifié.",
    "Un échantillon d’ADN humain-extraterrestre.",
    "Une carte mère endommagée.",
    "Un plan de fuite holographique.",
    "Un message d’alerte caché dans l’IA."
  ],
  historique: [
    "Un parchemin ancien trouvé sur les lieux.",
    "Une lettre codée datée de la veille du drame.",
    "Un médaillon portant des armoiries inconnues.",
    "Un témoin a vu une silhouette encapuchonnée.",
    "Un sceau brisé sur une lettre officielle.",
    "Un portrait griffonné à la hâte.",
    "Des traces de cire rouge sur le bureau.",
    "Un gant de velours taché de sang.",
    "Une boutonnière arrachée sur une veste historique.",
    "Un morceau de toile d’un drapeau.",
    "Une plume d’écriture brisée.",
    "Un carnet de comptes disparu.",
    "Des cendres de lettres brûlées dans la cheminée.",
    "Un livre ouvert à une page sur la trahison.",
    "Une broche de famille retrouvée sous une chaise.",
    "Un plan d’évasion dessiné sur un papier.",
    "Un extrait de discours raturé.",
    "Des traces de pas boueuses dans le salon.",
    "Un flacon de parfum renversé.",
    "Un billet de spectacle plié dans une poche.",
    "Un bouton doré portant un blason royal.",
    "Une coupe d’argent cassée.",
    "Un éventail ouvert sur une table.",
    "Un carnet de rendez-vous annoté.",
    "Une clef ancienne sous un coussin.",
    "Un mouchoir brodé d’initiales royales.",
    "Un message secret cousu dans une doublure.",
    "Un ticket de diligence du soir du crime.",
    "Des pétales de rose sur le parquet.",
    "Une médaille militaire oubliée.",
    "Un morceau de carte géographique annoté.",
    "Un agenda disparu.",
    "Une épingle cassée sur le tapis.",
    "Une fiole de poison vide.",
    "Un sablier brisé.",
    "Un témoin a entendu un cri dans la nuit.",
    "Un bracelet cassé retrouvé dans le jardin.",
    "Un morceau de clé ancienne.",
    "Un document officiel falsifié.",
    "Un mouchoir taché de sang."
  ]
};
