export const indices = {
  medieval: [
    // Indices matériels
    "Un morceau de tissu arraché trouvé près du lieu du crime.",
    "Une dague gravée oubliée dans la salle.",
    "Des traces de boue menant à la chambre de la victime.",
    "Un bijou appartenant à un(e) suspect(e) retrouvé sur place.",
    "Un gobelet de vin renversé contenant une étrange poudre.",
    "Un mouchoir brodé de lettres mystérieuses.",
    "Des cendres récentes dans la cheminée.",
    "Un morceau de corde usée sous le lit.",
    "Un plan du château griffonné à la hâte.",
    "Une clé de la tour retrouvée dans le jardin.",
    "Un morceau de pain empoisonné.",
    "Un arc caché dans la remise.",
    "Une cape mouillée retrouvée dans la cuisine.",
    "Un bracelet cassé sous la table.",
    "Un anneau glissé dans une chaussure.",
    "Un livre de prières ouvert à une page sur la trahison.",
    "Des herbes médicinales dispersées dans la chambre.",
    "Un message codé trouvé dans la cuisine.",
    "Un chandelier renversé.",
    "Des traces de sang menant aux écuries.",
    "Des plumes sur le sol près du corps.",
    "Un seau d’eau versé dans la salle juste avant le drame.",
    "Un morceau de cire sous le lit.",
    "Un coffre forcé mais rien ne manque.",
    "Un animal du domaine retrouvé blessé près du château.",
    "Une chaussure perdue dans la cour (mais appartenant à un enfant).",
    "Un tissu imbibé d’un liquide suspect (du vin renversé).",
    "Une porte secrète entrouverte.",
    "Un livre manquant dans la bibliothèque (juste prêté à quelqu’un).",
    "Un couteau de cuisine absent (utilisé pour le repas du soir).",
    // Rumeurs et témoignages
    "Un témoin affirme avoir entendu une dispute la veille.",
    "Un cri entendu au milieu de la nuit.",
    "Un serviteur prétend avoir vu la victime parler à un inconnu.",
    "Un braconnier a aperçu une silhouette dans la brume.",
    "La guérisseuse raconte avoir vu un(e) suspect(e) cacher quelque chose.",
    "On a entendu des pleurs dans l’aile nord la nuit du crime.",
    "Un domestique assure avoir vu un(e) suspect(e) rôder, mais il/elle se trompe.",
    // Fausses pistes
    "Des empreintes de pas sous la fenêtre, mais elles pourraient dater d’un autre jour.",
    "Un coffre forcé dans les appartements de la victime (mais rien ne manque).",
    "Un parfum inhabituel flotte dans la pièce (celui d’une visiteuse passée plus tôt).",
    "Une chaussure perdue dans la cour (appartenant à un enfant).",
    "Un morceau de pain empoisonné (jamais mangé).",
    "Une lettre d’amour cachée dans un coussin (mais ancienne).",
    "Un témoin a vu quelqu’un courir vers la chapelle (mais il faisait nuit).",
    "Un livre de recettes ouvert sur la table des domestiques.",
    "Un bout de tissu accroché à la porte (oublié depuis des jours).",
    "Un bruit de pas précipités dans la cour (en fait, un animal).",
    "Un message codé trouvé dans la cuisine (il s’agit d’une vieille recette)."
  ],

    renaissance: [
    // Indices matériels
    "Un gant brodé retrouvé dans l’atelier du peintre.",
    "Un flacon d’encre renversé sur une lettre inachevée.",
    "Des traces de pas menant à la bibliothèque.",
    "Une épingle à cheveux dorée trouvée sous le fauteuil du duc.",
    "Un parfum rare flotte dans l’air du salon.",
    "Un morceau de partition brûlé dans la cheminée.",
    "Un mouchoir taché de vin retrouvé dans la salle de bal.",
    "Un carnet de croquis déchiré.",
    "Un bijou de cour manquant à l’appel.",
    "Une clef cachée derrière un tableau.",
    "Un parchemin scellé dans une doublure de vêtement.",
    "Une perle roulée sous une table.",
    "Des cendres d’une lettre brûlée.",
    "Un médaillon contenant un portrait secret.",
    "Une chaussure boueuse retrouvée sur un tapis précieux.",
    "Une fiole vide d’un poison rare.",
    "Un plan de la ville annoté en secret.",
    "Un pétale de fleur écrasé sur le rebord d’une fenêtre.",
    "Une bague portant la devise d’un clan rival.",
    "Des traces de cire sur un parchemin.",
    "Un livre de comptes manquant.",
    "Un éventail cassé dans le jardin.",
    "Un bout de ruban déchiré.",
    "Une feuille de musique annotée.",
    "Un billet doux glissé dans un livre.",
    "Un pinceau taché de sang.",
    "Des traces de pas sur le carrelage.",
    "Un manteau oublié dans une ruelle.",
    "Un mouchoir brodé d’initiales inconnues.",
    "Un peigne d’ivoire fendu.",
    "Un bouquet fané dans les appartements de la victime.",
    "Des éclats de verre sous un meuble.",
    "Un coffre entrouvert dans la chambre.",
    "Un message codé dissimulé dans une reliure.",
    "Un parfum étranger sur un coussin.",
    "Un morceau de masque de bal déchiré.",
    "Une clé de coffre-fort disparue.",
    // Rumeurs et témoignages
    "Un témoin a vu un(e) suspect(e) rôder la nuit.",
    "Un témoin affirme avoir entendu une voix étrangère.",
    "Le chef de cuisine dit avoir croisé la victime tardivement.",
    "On raconte que la victime a reçu une lettre mystérieuse.",
    // Fausses pistes
    "Un gant brodé retrouvé mais appartenant à une invitée partie depuis longtemps.",
    "Un flacon d’encre renversé par un accident sans rapport.",
    "Un carnet de croquis déchiré par le chat du palais.",
    "Des cendres d’une lettre brûlée (recette de cuisine jetée).",
    "Un parfum rare (celui d’un ambassadeur étranger).",
    "Un médaillon contenant le portrait d’une inconnue.",
    "Des traces de cire sur un parchemin (banale maladresse).",
    "Un plan de la ville annoté (pour une fête future).",
    "Un bouquet fané (offert il y a plusieurs semaines)."
  ],

    victorien: [
    // Indices matériels
    "Un gant de dame retrouvé dans le jardin.",
    "Une montre à gousset arrêtée à l’heure du crime.",
    "Une lettre anonyme sur le bureau de la victime.",
    "Un foulard parfumé caché sous le lit.",
    "Des traces de boue sur le tapis du salon.",
    "Un verre de liqueur renversé dans la bibliothèque.",
    "Un bouton de manchette sous le fauteuil.",
    "Un peigne d’argent cassé.",
    "Un billet de train non utilisé.",
    "Un flacon vide d’opium.",
    "Un pansement ensanglanté trouvé dans la corbeille.",
    "Un chapeau oublié dans le hall.",
    "Un ticket de théâtre dans une poche.",
    "Un carnet d’adresses ouvert à un nom en particulier.",
    "Des empreintes de pas dans la serre.",
    "Un fragment de miroir brisé dans la chambre.",
    "Un parfum inconnu sur un mouchoir.",
    "Une trace de rouge à lèvres sur une tasse.",
    "Un morceau de soie près de la fenêtre.",
    "Un bouton arraché de la veste d’un suspect.",
    "Des empreintes de bottes dans la boue.",
    "Un agenda déchiré.",
    "Des gants d’homme dans la chambre de la victime.",
    "Un reçu bancaire brûlé à moitié.",
    // Rumeurs et témoignages
    "La gouvernante prétend avoir vu le majordome sortir précipitamment.",
    "Un voisin a entendu une voix forte près de la serre.",
    "On dit que la victime avait un rendez-vous secret.",
    "Un enfant du personnel affirme avoir vu une silhouette mystérieuse.",
    "La cuisinière croit avoir entendu la victime parler à voix basse, mais elle confond avec la radio.",
    "Un invité affirme avoir croisé la victime dans le parc après l’heure du crime.",
    "Un témoin a entendu une dispute, mais elle concernait un autre sujet.",
    // Fausses pistes
    "Un livre d’herboristerie annoté, mais il appartient à la bibliothèque.",
    "Une clé manquante au trousseau du majordome (elle était tombée derrière un meuble).",
    "Des pétales de rose sur le rebord de la fenêtre (décoration habituelle).",
    "Un ticket de théâtre dans la poche d’une veste (datant de la semaine passée).",
    "Un parfum inconnu sur un mouchoir (en fait, celui de la femme de chambre).",
    "Un bouton arraché de la veste d’un suspect (mais lors d’une bousculade la veille).",
    "Un fragment de miroir brisé dans la chambre (accident domestique).",
    "Des empreintes de bottes dans la boue (celles du jardinier).",
    "Un agenda déchiré (mais par un enfant de la maison)."
  ],

    western: [
    // Indices matériels
    "Un colt encore chaud trouvé derrière le saloon.",
    "Des traces de bottes menant à l’écurie.",
    "Un foulard ensanglanté retrouvé près du puits.",
    "Un as de pique glissé sous la porte.",
    "Des pièces d’or tombées le long de la route.",
    "Un mouchoir brodé dans la poche d’un suspect.",
    "Une cartouche vide dans la chambre.",
    "Un sombrero oublié sur la clôture.",
    "Un cheval sellé abandonné près de la rivière.",
    "Une bouteille de whisky vide sous le lit.",
    "Un bandana imbibé de sueur retrouvé dans la grange.",
    "Un morceau de corde effilochée.",
    "Un gant de cuir perdu dans la ruelle.",
    "Un éclat de miroir sur la piste.",
    "Des graines de tabac répandues sur le sol.",
    "Un chapeau troué accroché à un clou.",
    "Une lettre froissée dans la poche d’un pantalon.",
    "Un mouchoir taché de poudre noire.",
    "Une étoile de shérif abîmée.",
    "Un billet de banque déchiré.",
    "Une trace de sang sur la selle d’un cheval.",
    "Un bouton de chemise arraché.",
    "Un cigare à moitié consumé.",
    "Un éclat de verre dans l’abreuvoir.",
    "Un morceau de carte au trésor.",
    // Rumeurs et témoignages
    "Un témoin a entendu un coup de feu la veille.",
    "Un témoin a vu un cavalier partir au galop.",
    "Le barman a vu deux clients se disputer violemment.",
    "La postière raconte que la victime a reçu une lettre étrange.",
    "Un cow-boy affirme avoir vu une silhouette près du cimetière.",
    // Fausses pistes
    "Un bandana imbibé de sueur (oublié depuis des jours).",
    "Un gant de cuir perdu dans la ruelle (celui d’un passant).",
    "Un morceau de corde effilochée (changement de clôture).",
    "Un cheval sellé abandonné (problème d’écurie).",
    "Une lettre froissée (plainte à propos du saloon).",
    "Un bouton de chemise arraché (bagarre sans rapport).",
    "Un cigare à moitié consumé (habitude du shérif).",
    "Un éclat de verre dans l’abreuvoir (bagarre d’ivrognes).",
    "Un morceau de carte au trésor (jeu d’enfants)."
  ],

    contemporain: [
    // Indices matériels
    "Un téléphone portable oublié sur les lieux du crime.",
    "Un ticket de métro retrouvé près du corps.",
    "Une empreinte digitale sur un verre.",
    "Un badge d’accès oublié dans un ascenseur.",
    "Une clé USB contenant des fichiers suspects.",
    "Une trace de rouge à lèvres sur une chemise.",
    "Un stylo publicitaire d’une société concurrente.",
    "Des images de vidéosurveillance effacées.",
    "Un badge d’identité non attribué.",
    "Une carte bancaire oubliée.",
    "Un carnet d’adresses déchiré.",
    "Un reçu de paiement dans une poche.",
    "Des résidus de poudre blanche sur une étagère.",
    "Un agenda ouvert à la date du drame.",
    "Une photo compromettante sur un smartphone.",
    "Un badge de parking oublié.",
    "Un morceau de ruban adhésif.",
    "Un extrait de conversation WhatsApp.",
    "Une boîte de médicaments vide.",
    "Un plan d’accès griffonné.",
    // Rumeurs et témoignages
    "Un voisin prétend avoir entendu des éclats de voix.",
    "La victime aurait reçu un appel mystérieux la veille.",
    "Un collègue évoque une querelle récente.",
    "Un témoin affirme avoir vu la victime tard, mais se trompe de jour.",
    "Un voisin décrit une voiture suspecte (en réalité celle d’un client).",
    "Une conversation WhatsApp sortie de son contexte.",
    // Fausses pistes
    "Un badge d’accès à la salle informatique, oublié la veille.",
    "Un chewing-gum mâché collé sous la table (appartient à un client régulier).",
    "Un ticket de cinéma du soir du crime, mais la séance était annulée.",
    "Un courrier anonyme dans la boîte aux lettres (publicité).",
    "Une trace de pneu inhabituelle (livreur du matin).",
    "Un gobelet de café renversé (oublié depuis plusieurs jours).",
    "Un badge de parking oublié (par la voisine).",
    "Un badge d’accès oublié dans un ascenseur (du livreur).",
    "Des traces de peinture sur les chaussures (travaux dans l’immeuble).",
    "Un ticket de restaurant (mais à une autre table).",
    "Un double des clés retrouvé sous un paillasson (celui du concierge).",
    "Un reçu de paiement dans une poche (achat sans rapport)."
  ],

    futuriste: [
    // Indices matériels
    "Un implant électronique désactivé retrouvé sur la scène.",
    "Des traces de nano-robots dans le système de ventilation.",
    "Une carte d’accès biométrique usurpée.",
    "Un rapport d’IA effacé mystérieusement.",
    "Une empreinte digitale falsifiée.",
    "Un hologramme brouillé enregistré avant le crime.",
    "Un résidu de liquide cryogénique.",
    "Un drone de surveillance retrouvé endommagé.",
    "Un message codé sur un terminal informatique.",
    "Une capsule de médicaments vides.",
    "Un circuit imprimé brûlé.",
    "Des logs système supprimés.",
    "Un badge d’accès à un secteur interdit.",
    "Un microprocesseur manquant sur le robot assistant.",
    "Des traces d’ADN modifié.",
    "Un script informatique en cours d’exécution.",
    "Une signature énergétique inconnue.",
    "Un gant de manipulation robotique.",
    "Un fragment de puce mémoire.",
    "Un plan de la station annoté à la main.",
    // Rumeurs et témoignages
    "Un témoin IA prétend avoir observé une anomalie temporelle.",
    "Un technicien affirme avoir vu un androïde s’éloigner en urgence.",
    "Une alerte sonore a retenti dans le secteur 4 à l’heure du crime.",
    "Un membre d’équipage dit avoir croisé un clone non autorisé.",
    // Fausses pistes
    "Un badge de maintenance non autorisé (oublié lors d’une réparation précédente).",
    "Une empreinte énergétique sur la console (problème de surcharge récurrent).",
    "Un gant de manipulation atomique (oublié dans le sas depuis un test).",
    "Des traces d’ADN modifié (résultat d’une expérience officielle).",
    "Un journal de bord effacé (mise à jour automatique du système).",
    "Un fragment de puce mémoire (pièce de rechange tombée d’une trousse).",
    "Un message audio crypté (ancien test de communication).",
    "Un plan de fuite holographique (programme d’exercice d’évacuation).",
    "Un rapport de maintenance falsifié (simple erreur humaine)."
  ],

    historique: [
    // Indices matériels
    "Un parchemin ancien trouvé sur les lieux.",
    "Une lettre codée datée de la veille du drame.",
    "Un médaillon portant des armoiries inconnues.",
    "Un sceau brisé sur une lettre officielle.",
    "Un portrait griffonné à la hâte.",
    "Des traces de cire rouge sur le bureau.",
    "Un gant de velours taché de sang.",
    "Une boutonnière arrachée sur une veste historique.",
    "Un morceau de toile d’un drapeau.",
    "Une plume d’écriture brisée.",
    "Un carnet de comptes disparu.",
    "Des cendres de lettres brûlées dans la cheminée.",
    "Un livre ouvert à une page sur la trahison.",
    "Une broche de famille retrouvée sous une chaise.",
    "Un plan d’évasion dessiné sur un papier.",
    "Un extrait de discours raturé.",
    "Des traces de pas boueuses dans le salon.",
    "Un flacon de parfum renversé.",
    "Un billet de spectacle plié dans une poche.",
    "Un bouton doré portant un blason royal.",
    // Rumeurs et témoignages
    "Un témoin a vu une silhouette encapuchonnée.",
    "Un serviteur affirme avoir entendu la victime parler à une voix inconnue.",
    "Un voisin a entendu une dispute dans le bureau.",
    "On raconte que la victime préparait une fuite.",
    "Un témoin a entendu un cri dans la nuit.",
    // Fausses pistes
    "Un billet de spectacle (datant d’un événement passé).",
    "Des pétales de rose sur le parquet (restes d’une fête).",
    "Un sablier brisé (accident lors d’un nettoyage).",
    "Un carnet de rendez-vous annoté (rendez-vous professionnels).",
    "Un bouton doré portant un blason royal (uniforme oublié).",
    "Une clef ancienne sous un coussin (oubliée depuis longtemps).",
    "Un extrait de discours raturé (brouillon de discours politique).",
    "Un plan d’évasion dessiné (jeu d’enfants).",
    "Un document officiel falsifié (projet d’écriture de roman)."
  ]
};
