// SRC/JS/liensAvecVictime.js

export const liensAvecVictime = {
  medieval: [
    "Vous êtes le frère/la sœur bâtard(e) de la victime.",
    "Vous étiez l’écuyer/la suivante de la victime.",
    "Vous deviez une dîme à la victime.",
    "La victime vous avait accusé(e) de vol au marché.",
    "Vous étiez rival(e) pour une place à la cour.",
    "Vous étiez fiancé(e) à la victime, mais le mariage a été annulé.",
    "La victime a dénoncé votre famille à un seigneur.",
    "Vous avez partagé la captivité avec la victime.",
    "La victime vous a humilié(e) lors d’un banquet.",
    "Vous êtes le/la filleul(e) de la victime.",
    "La victime vous a battu(e) lors d’un tournoi.",
    "Vous étiez le/la protégé(e) de la victime.",
    "Vous avez grandi ensemble dans le même fief.",
    "La victime a ruiné votre réputation auprès du seigneur.",
    "Vous deviez de l’argent à la victime pour un cheval.",
    "La victime a tué un membre de votre famille.",
    "Vous étiez complice de braconnage avec la victime.",
    "La victime connaissait un secret honteux sur vous.",
    "Vous étiez les héritiers d’un même domaine.",
    "Vous soupçonniez la victime de sorcellerie.",
    "Vous aviez volé des vivres à la victime.",
    "La victime vous a battu(e) aux dés dans la taverne.",
    "Vous étiez amoureux(se) de la même personne.",
    "Vous étiez l’ennemi(e) juré(e) de la victime.",
    "La victime vous avait blessé(e) lors d’un duel.",
    "Vous étiez l’apprenti(e) de la victime.",
    "Vous avez été chassé(e) de la cour à cause de la victime.",
    "Vous étiez le/la confident(e) de la victime.",
    "Vous aviez partagé une mission dangereuse avec la victime.",
    "La victime vous a refusé une dot.",
    "Vous étiez soupçonné(e) d’hérésie par la victime.",
    "Vous aviez échangé des lettres secrètes avec la victime.",
    "La victime a trahi votre clan.",
    "Vous deviez protéger la victime par serment.",
    "La victime vous soupçonnait de trahison.",
    "Vous étiez en lice contre la victime pour le titre de prévôt.",
    "Vous avez perdu un procès contre la victime.",
    "La victime vous a infligé un châtiment injuste.",
    "Vous faisiez partie d’un même groupe de brigands.",
    "Vous étiez ami(e)s d’enfance, mais vous étiez brouillé(e)s."
  ],
  renaissance: [
    "Vous étiez l’apprenti(e) de la victime dans son atelier.",
    "La victime a financé vos études.",
    "Vous étiez rival(e) pour une commande artistique.",
    "Vous aviez une liaison secrète avec la victime.",
    "La victime a ruiné votre réputation auprès du duc.",
    "Vous deviez de l’argent à la victime pour une œuvre.",
    "Vous étiez son/sa secrétaire personnel(le).",
    "La victime vous soupçonnait d’espionnage.",
    "Vous aviez perdu un procès contre la victime.",
    "Vous étiez héritier/ère d’un même mécène.",
    "Vous accusiez la victime de plagiat.",
    "Vous étiez complice d’un vol d’art avec la victime.",
    "La victime vous a dénoncé(e) à l’Inquisition.",
    "Vous étiez en concurrence pour un poste à la cour.",
    "La victime connaissait un secret d’État sur vous.",
    "Vous étiez les amants éconduits de la même personne.",
    "Vous étiez parenté(e)s éloigné(e)s.",
    "Vous avez été évincé(e) d’un bal par la victime.",
    "La victime a fait annuler votre mariage.",
    "Vous étiez son/sa modèle favori(te).",
    "La victime a défendu votre honneur lors d’un duel.",
    "Vous aviez partagé un voyage périlleux.",
    "La victime a piqué votre invention.",
    "Vous étiez complice d’un faux monnayage.",
    "La victime vous a humilié(e) lors d’un banquet.",
    "Vous étiez en affaires ensemble.",
    "La victime vous a accusé(e) de sorcellerie.",
    "Vous étiez les enfants de deux familles rivales.",
    "La victime a fait enfermer un membre de votre famille.",
    "Vous deviez livrer un message secret pour la victime.",
    "Vous étiez le/la protégé(e) d’un même mécène.",
    "La victime vous a inspiré un grand poème.",
    "Vous étiez son/sa maître(sse) de danse.",
    "Vous avez partagé les secrets d’un laboratoire.",
    "La victime a détruit une de vos œuvres.",
    "Vous étiez l’ami(e) fidèle de la victime.",
    "Vous aviez été exilé(e) à cause de la victime.",
    "La victime a révélé votre véritable identité.",
    "Vous étiez l’élève favori(te) de la victime.",
    "Vous aviez partagé un secret de famille avec la victime."
  ],
  victorien: [
    "Vous étiez l’assistant(e) scientifique de la victime.",
    "La victime détenait une lettre compromettante sur vous.",
    "Vous étiez en conflit pour un héritage.",
    "La victime a ruiné votre réputation dans la haute société.",
    "Vous étiez soupçonné(e) d’espionnage industriel par la victime.",
    "Vous aviez une liaison secrète avec la victime.",
    "Vous étiez son/sa secrétaire personnel(le).",
    "La victime vous avait écarté(e) d’un bal prestigieux.",
    "Vous étiez le/la rival(e) d’affaires de la victime.",
    "La victime a dénoncé vos dettes à la banque.",
    "Vous étiez ses cousin(e)s éloigné(e)s.",
    "Vous deviez une grosse somme à la victime.",
    "La victime avait menacé de révéler un secret de famille.",
    "Vous aviez été soupçonné(e) d’un vol de bijoux.",
    "Vous étiez son/sa protégé(e) lors de votre arrivée à Londres.",
    "Vous étiez soupçonné(e) d’avoir courtisé le/la fiancé(e) de la victime.",
    "La victime a fait échouer votre mariage.",
    "Vous étiez le/la tuteur/tutrice légal(e) d’un de ses enfants.",
    "Vous aviez partagé une expédition lointaine avec la victime.",
    "La victime vous a humilié(e) lors d’un dîner mondain.",
    "Vous étiez le/la voisin(e) de la victime.",
    "La victime avait ruiné vos finances.",
    "Vous aviez été sauvé(e) par la victime dans votre jeunesse.",
    "Vous étiez les amants d’un même homme/femme.",
    "La victime connaissait la vérité sur un scandale passé.",
    "Vous étiez le/la directeur/directrice de la victime.",
    "Vous aviez perdu un procès contre la victime.",
    "La victime a fait enfermer un de vos proches.",
    "Vous étiez les héritiers d’un même testament.",
    "La victime vous soupçonnait d’avoir falsifié des documents.",
    "Vous aviez partagé un secret médical.",
    "La victime vous a volé une invention.",
    "Vous étiez le/la locataire de la victime.",
    "La victime a refusé de vous épouser.",
    "Vous étiez son/sa maître(sse) d’hôtel.",
    "Vous aviez été piégé(e) par la victime lors d’une affaire.",
    "La victime vous avait battu(e) à un jeu de cartes.",
    "Vous étiez le/la partenaire de bridge de la victime.",
    "La victime avait tenté de vous discréditer publiquement.",
    "Vous étiez l’ami(e) d’enfance de la victime."
  ],
  western: [
    "Vous étiez le/la partenaire de jeu de la victime au saloon.",
    "La victime vous devait de l’argent au poker.",
    "Vous étiez rival(e)s pour la même terre.",
    "La victime avait volé votre cheval.",
    "Vous étiez complice d’un braquage avec la victime.",
    "Vous aviez le même amour secret.",
    "Vous étiez le/la shérif adjoint(e) de la victime.",
    "La victime avait fait enfermer un membre de votre famille.",
    "Vous étiez le/la barman/bargirl du saloon fréquenté par la victime.",
    "La victime vous soupçonnait de tricherie.",
    "Vous aviez été blessé(e) lors d’un duel avec la victime.",
    "Vous étiez les seuls témoins d’un hold-up.",
    "La victime avait ruiné votre réputation en ville.",
    "Vous étiez le/la voisin(e) de ranch de la victime.",
    "La victime avait incendié vos récoltes.",
    "Vous étiez le/la complice d’un trafic de bétail.",
    "Vous aviez partagé une chasse au trésor.",
    "La victime vous a battu(e) lors d’une course de chevaux.",
    "Vous étiez son/sa apprenti(e) cowboy/cowgirl.",
    "La victime connaissait votre passé criminel.",
    "Vous étiez le/la médecin du village.",
    "La victime vous a humilié(e) au saloon.",
    "Vous étiez le/la conducteur/conductrice de diligence pour la victime.",
    "Vous étiez l’ancien(ne) amant(e) de la victime.",
    "La victime avait tenté de vous faire chanter.",
    "Vous étiez complice d’une attaque de train.",
    "La victime avait fait échouer votre mariage.",
    "Vous étiez le/la propriétaire du saloon.",
    "La victime avait volé votre or.",
    "Vous étiez les seuls survivants d’une attaque.",
    "La victime a témoigné contre vous lors d’un procès.",
    "Vous étiez le/la maréchal(e)-ferrant(e) qui s’occupait de ses chevaux.",
    "La victime a tué votre chien.",
    "Vous étiez le/la chef(fe) de la milice locale.",
    "La victime avait tenté de vous empoisonner.",
    "Vous étiez les deux pionniers d’une nouvelle ville.",
    "La victime vous a accusé(e) de vol.",
    "Vous étiez le/la postier/postière en ville.",
    "La victime avait volé votre fiancé(e).",
    "Vous étiez le/la fossoyeur(se) qui a enterré un de ses proches."
  ],
  contemporain: [
    "Vous étiez collègues dans la même entreprise.",
    "La victime avait ruiné votre carrière à cause d’une dénonciation.",
    "Vous aviez une liaison secrète avec la victime.",
    "Vous étiez voisins/voisines d’immeuble.",
    "La victime connaissait un secret gênant sur vous.",
    "Vous étiez en procès pour un héritage.",
    "La victime avait supprimé vos données cruciales.",
    "Vous étiez en compétition pour une promotion.",
    "La victime avait diffusé une rumeur à votre sujet.",
    "Vous étiez son/sa supérieur(e) hiérarchique.",
    "Vous aviez été licencié(e) par la victime.",
    "La victime vous devait de l’argent.",
    "Vous étiez le/la baby-sitter de ses enfants.",
    "La victime avait volé votre idée de projet.",
    "Vous partagiez le même appartement.",
    "La victime avait fait échouer votre mariage.",
    "Vous étiez son/sa coach sportif(ve).",
    "La victime avait détruit une de vos œuvres.",
    "Vous étiez les deux fondateurs/fondatrices d’une start-up.",
    "La victime avait porté plainte contre vous.",
    "Vous étiez son/sa meilleur(e) ami(e) d’enfance.",
    "La victime vous avait accusé(e) de harcèlement.",
    "Vous étiez le/la chef(fe) de projet de la victime.",
    "La victime avait trahi votre confiance.",
    "Vous aviez été hospitalisé(e) à cause de la victime.",
    "La victime avait publié un article calomnieux sur vous.",
    "Vous étiez en couple avec l’ex de la victime.",
    "La victime avait saboté votre entretien d’embauche.",
    "Vous étiez son/sa voisin(e) de bureau.",
    "La victime avait volé un objet précieux chez vous.",
    "Vous étiez le/la notaire de la victime.",
    "La victime avait fait licencier un de vos proches.",
    "Vous étiez son/sa associé(e) dans une affaire louche.",
    "La victime connaissait votre double vie.",
    "Vous étiez en conflit pour la garde d’un animal.",
    "La victime avait détruit votre réputation sur les réseaux.",
    "Vous étiez le/la propriétaire de son logement.",
    "La victime avait tenté de vous faire chanter.",
    "Vous étiez le/la meilleur(e) client(e) de son commerce.",
    "La victime avait tenté de hacker votre compte."
  ],
  futuriste: [
    "Vous étiez les copilotes du même vaisseau.",
    "La victime vous accusait de sabotage.",
    "Vous étiez les seuls survivants d’une mission ratée.",
    "La victime avait piraté vos données confidentielles.",
    "Vous étiez en concurrence pour le commandement.",
    "La victime avait volé un prototype que vous aviez conçu.",
    "Vous étiez partenaires de recherche.",
    "La victime connaissait un secret sur votre origine.",
    "Vous étiez l’ingénieur(e) responsable de ses modules.",
    "La victime avait effacé votre mémoire partiellement.",
    "Vous étiez en couple avec l’ex de la victime.",
    "La victime vous avait dénoncé(e) pour trahison.",
    "Vous étiez le/la seul(e) à comprendre son langage.",
    "La victime avait tenté de saboter vos expériences.",
    "Vous étiez son/sa mentor/mentore en science.",
    "La victime avait tenté de vous éliminer d’une expédition.",
    "Vous étiez en conflit pour l’accès à un laboratoire.",
    "La victime avait modifié votre code génétique.",
    "Vous étiez partenaires dans le trafic de nano-robots.",
    "La victime vous avait accusé(e) d’espionnage.",
    "Vous étiez les héritiers d’un même brevet.",
    "La victime avait tenté de vous effacer de l’IA centrale.",
    "Vous étiez le/la chef(fe) de la sécurité de la victime.",
    "La victime avait volé votre compagnon androïde.",
    "Vous étiez son/sa principal(e) testeur/testeuse.",
    "La victime avait dérobé vos résultats d’expérience.",
    "Vous étiez son/sa assistant(e) de bord.",
    "La victime vous avait menacé(e) de tout révéler.",
    "Vous étiez en mission secrète pour la même agence.",
    "La victime avait saboté votre module de survie.",
    "Vous étiez le/la concepteur/conceptrice de son IA.",
    "La victime avait modifié votre avatar numérique.",
    "Vous étiez en compétition pour la même promotion spatiale.",
    "La victime avait tenté de vous piéger lors d’une mission.",
    "Vous étiez son/sa partenaire de capsule.",
    "La victime avait tenté de vous faire passer pour un traître.",
    "Vous étiez le/la responsable de sa cryogénisation.",
    "La victime avait hacké vos souvenirs.",
    "Vous étiez son/sa principal(e) collaborateur/collaboratrice.",
    "La victime avait menacé de vous exiler sur une planète lointaine."
  ],

  historique: [
    "Vous étiez le rival politique de la victime.",
    "La victime a contrecarré vos ambitions au sein du gouvernement.",
    "Vous aviez une liaison secrète avec la victime.",
    "Vous étiez l’élève favori(te) de la victime, mais une trahison vous a séparés.",
    "La victime connaissait un secret d’état compromettant pour vous.",
    "Vous étiez l’héritier(ère) potentiel(le) du trône, mais la victime a été préférée.",
    "Vous aviez été exilé(e) à cause d’une dénonciation de la victime.",
    "Vous étiez en concurrence pour l’amour d’un(e) souverain(e).",
    "La victime était votre mentor dans l’art ou la science.",
    "Vous aviez perdu un duel d’honneur contre la victime.",
    "La victime vous a dénoncé(e) comme espion(ne).",
    "Vous étiez soupçonné(e) de comploter contre la victime.",
    "La victime a fait emprisonner un proche de votre famille.",
    "Vous étiez le/la secrétaire particulier(ère) de la victime.",
    "Vous deviez une somme considérable à la victime.",
    "La victime vous avait humilié(e) publiquement lors d’un bal.",
    "Vous étiez l’ancien(ne) meilleur(e) ami(e) de la victime, aujourd’hui brouillé(e)s.",
    "Vous aviez partagé une expédition scientifique avec la victime.",
    "La victime avait révélé vos origines modestes à la cour.",
    "Vous étiez le/la principal(e) conseiller(ère) de la victime.",
    "La victime vous accusait de trahison.",
    "Vous étiez en rivalité artistique avec la victime.",
    "La victime avait publié un pamphlet contre vous.",
    "Vous étiez chargé(e) de protéger la victime lors d’un attentat manqué.",
    "La victime a épousé la personne que vous aimiez.",
    "Vous étiez le/la médecin personnel(le) de la victime.",
    "La victime a dérobé votre invention ou découverte.",
    "Vous étiez frère/sœur de la victime, mais héritier(ère) déchu(e).",
    "La victime avait fait exécuter un de vos alliés.",
    "Vous aviez partagé un exil avec la victime.",
    "La victime possédait des lettres compromettantes vous concernant.",
    "Vous étiez le/la destinataire d’une confession écrite par la victime.",
    "La victime vous soupçonnait d’intelligence avec l’ennemi.",
    "Vous étiez l’ami(e) d’enfance de la victime, mais un événement tragique vous a séparés.",
    "La victime vous avait écarté(e) d’une mission diplomatique.",
    "Vous étiez en conflit pour la direction d’une académie ou d’une institution.",
    "La victime vous avait accusé(e) de vol d’une œuvre ou d’une idée.",
    "Vous étiez l’auteur(e) d’un discours que la victime a revendiqué.",
    "La victime avait détruit votre réputation auprès de la monarchie.",
    "Vous étiez l’unique témoin d’un secret d’état avec la victime."
  ]
};
