// SRC/JS/lieux.js

const lieuxParEpoque = {
  medieval: [
    { nom: "château", genre: "m" },
    { nom: "grande salle", genre: "f" },
    { nom: "forêt", genre: "f" },
    { nom: "cave", genre: "f" },
    { nom: "donjon", genre: "m" },
    { nom: "chapelle", genre: "f" },
    { nom: "remparts", genre: "m" },
    { nom: "écuries", genre: "f" },
    { nom: "salle d'armes", genre: "f" },
    { nom: "jardin potager", genre: "m" },
    { nom: "crypte", genre: "f" },
    { nom: "tour de guet", genre: "f" },
    { nom: "bastion", genre: "m" },
    { nom: "cellier", genre: "m" },
    { nom: "moulin", genre: "m" },
    { nom: "grange", genre: "f" },
    { nom: "puits", genre: "m" },
    { nom: "herboristerie", genre: "f" },
    { nom: "taverne", genre: "f" },
    { nom: "place du village", genre: "f" },
    { nom: "potence", genre: "f" },
    { nom: "chemin de ronde", genre: "m" },
    { nom: "pigeonnier", genre: "m" },
    { nom: "ruisseau", genre: "m" },
    { nom: "terre-plein", genre: "m" },
    { nom: "oratoire", genre: "m" },
    { nom: "bergerie", genre: "f" },
    { nom: "forge", genre: "f" },
    { nom: "cabane du garde", genre: "f" },
    { nom: "silo à grain", genre: "m" }
  ],

  victorien: [
    { nom: "manoir", genre: "m" },
    { nom: "bibliothèque", genre: "f" },
    { nom: "salon", genre: "m" },
    { nom: "jardin", genre: "m" },
    { nom: "sous-sol", genre: "m" },
    { nom: "salle de bal", genre: "f" },
    { nom: "fumoir", genre: "m" },
    { nom: "cuisine", genre: "f" },
    { nom: "orangerie", genre: "f" },
    { nom: "chambre forte", genre: "f" },
    { nom: "serre", genre: "f" },
    { nom: "grenier", genre: "m" },
    { nom: "cabinet d'étude", genre: "m" },
    { nom: "galerie de portraits", genre: "f" },
    { nom: "salle de musique", genre: "f" },
    { nom: "hall d'entrée", genre: "m" },
    { nom: "salle à manger", genre: "f" },
    { nom: "cabinet médical", genre: "m" },
    { nom: "cour intérieure", genre: "f" },
    { nom: "parc", genre: "m" },
    { nom: "loge du gardien", genre: "f" },
    { nom: "atelier d'artiste", genre: "m" },
    { nom: "dressing", genre: "m" },
    { nom: "salle d'eau", genre: "f" },
    { nom: "roseraie", genre: "f" },
    { nom: "palier", genre: "m" },
    { nom: "office", genre: "m" },
    { nom: "escalier secret", genre: "m" },
    { nom: "ponton sur le lac", genre: "m" },
    { nom: "chambre d’enfant", genre: "f" }
  ],

  futuriste: [
    { nom: "station orbitale", genre: "f" },
    { nom: "laboratoire", genre: "m" },
    { nom: "cyber-café", genre: "m" },
    { nom: "dôme botanique", genre: "m" },
    { nom: "soute", genre: "f" },
    { nom: "cabine de pilotage", genre: "f" },
    { nom: "couloir stérile", genre: "m" },
    { nom: "hangar à drones", genre: "m" },
    { nom: "salle des machines", genre: "f" },
    { nom: "observatoire", genre: "m" },
    { nom: "pont principal", genre: "m" },
    { nom: "module médical", genre: "m" },
    { nom: "salle de téléportation", genre: "f" },
    { nom: "quartiers d’équipage", genre: "m" },
    { nom: "serre hydroponique", genre: "f" },
    { nom: "salle de cryogénie", genre: "f" },
    { nom: "baie de chargement", genre: "f" },
    { nom: "centre de commandement", genre: "m" },
    { nom: "zone de quarantaine", genre: "f" },
    { nom: "salle de repos", genre: "f" },
    { nom: "atelier robotique", genre: "m" },
    { nom: "ascenseur gravitationnel", genre: "m" },
    { nom: "salle de simulation", genre: "f" },
    { nom: "dépôt d’armes énergétiques", genre: "m" },
    { nom: "coffre-fort de données", genre: "m" },
    { nom: "salle de réunion holographique", genre: "f" },
    { nom: "plateforme d’atterrissage", genre: "f" },
    { nom: "réacteur principal", genre: "m" },
    { nom: "sas d’évacuation", genre: "m" },
    { nom: "capsule d’exploration", genre: "f" }
  ],

  contemporain: [
    { nom: "salle de réunion", genre: "f" },
    { nom: "bureau open space", genre: "m" },
    { nom: "parking souterrain", genre: "m" },
    { nom: "hall d'entrée", genre: "m" },
    { nom: "cafétéria", genre: "f" },
    { nom: "rooftop", genre: "m" },
    { nom: "appartement", genre: "m" },
    { nom: "garage", genre: "m" },
    { nom: "salle de sport", genre: "f" },
    { nom: "cuisine", genre: "f" },
    { nom: "ascenseur", genre: "m" },
    { nom: "local à poubelles", genre: "m" },
    { nom: "toilettes", genre: "f" },
    { nom: "couloir", genre: "m" },
    { nom: "réserve", genre: "f" },
    { nom: "sous-sol", genre: "m" },
    { nom: "studio de musique", genre: "m" },
    { nom: "terrasse", genre: "f" },
    { nom: "salle d’attente", genre: "f" },
    { nom: "vestiaire", genre: "m" },
    { nom: "salle de classe", genre: "f" },
    { nom: "jardin partagé", genre: "m" },
    { nom: "palier", genre: "m" },
    { nom: "bibliothèque municipale", genre: "f" },
    { nom: "salle informatique", genre: "f" },
    { nom: "laverie automatique", genre: "f" },
    { nom: "bar à cocktails", genre: "m" },
    { nom: "restaurant", genre: "m" },
    { nom: "cave à vin", genre: "f" },
    { nom: "cabinet médical", genre: "m" }
  ],

  western: [
    { nom: "saloon", genre: "m" },
    { nom: "ranch", genre: "m" },
    { nom: "banque", genre: "f" },
    { nom: "prison", genre: "f" },
    { nom: "corral", genre: "m" },
    { nom: "gare", genre: "f" },
    { nom: "poste du shérif", genre: "m" },
    { nom: "cabane du trappeur", genre: "f" },
    { nom: "mine d’or", genre: "f" },
    { nom: "diligence", genre: "f" },
    { nom: "cimetière", genre: "m" },
    { nom: "église", genre: "f" },
    { nom: "épicerie", genre: "f" },
    { nom: "forge", genre: "f" },
    { nom: "ruelle sombre", genre: "f" },
    { nom: "pont suspendu", genre: "m" },
    { nom: "pensionnat", genre: "m" },
    { nom: "barber shop", genre: "m" },
    { nom: "auberge", genre: "f" },
    { nom: "réserve indienne", genre: "f" },
    { nom: "champ de bataille", genre: "m" },
    { nom: "rivière", genre: "f" },
    { nom: "colline du pendu", genre: "f" },
    { nom: "poste de télégraphe", genre: "m" },
    { nom: "wagon abandonné", genre: "m" },
    { nom: "stand de tir", genre: "m" },
    { nom: "cabane du prospecteur", genre: "f" },
    { nom: "prairie", genre: "f" },
    { nom: "ruisseau asséché", genre: "m" },
    { nom: "grange", genre: "f" }
  ],

  renaissance: [
    { nom: "palais ducal", genre: "m" },
    { nom: "atelier d’artiste", genre: "m" },
    { nom: "salle des festins", genre: "f" },
    { nom: "jardins à l’italienne", genre: "m" },
    { nom: "loggia", genre: "f" },
    { nom: "chapelle privée", genre: "f" },
    { nom: "bibliothèque", genre: "f" },
    { nom: "salon de musique", genre: "m" },
    { nom: "cour intérieure", genre: "f" },
    { nom: "galerie d’art", genre: "f" },
    { nom: "salle de bal", genre: "f" },
    { nom: "cuisine", genre: "f" },
    { nom: "antichambre", genre: "f" },
    { nom: "terrazza", genre: "f" },
    { nom: "salle à manger", genre: "f" },
    { nom: "laboratoire d’alchimie", genre: "m" },
    { nom: "fontaine", genre: "f" },
    { nom: "orangerie", genre: "f" },
    { nom: "atelier du sculpteur", genre: "m" },
    { nom: "studyolo", genre: "m" },
    { nom: "appartement du prince", genre: "m" },
    { nom: "porte secrète", genre: "f" },
    { nom: "dortoir des dames", genre: "m" },
    { nom: "logis du chambellan", genre: "m" },
    { nom: "cabinet de curiosités", genre: "m" },
    { nom: "serre aux plantes rares", genre: "f" },
    { nom: "escalier monumental", genre: "m" },
    { nom: "pavillon de chasse", genre: "m" },
    { nom: "balcon sur la place", genre: "m" },
    { nom: "portique", genre: "m" }
  ],

  historique: [
    { nom: "Colisée", genre: "f" },
    { nom: "thermes", genre: "m" },
    { nom: "forum", genre: "m" },
    { nom: "pyramide de Khéops", genre: "f" },
    { nom: "palais royal", genre: "m" },
    { nom: "bibliothèque d'Alexandrie", genre: "f" },
    { nom: "amphithéâtre", genre: "m" },
    { nom: "abbaye", genre: "f" },
    { nom: "observatoire", genre: "m" },
    { nom: "catacombes", genre: "f" },
    { nom: "temple de Zeus", genre: "m" },
    { nom: "forteresse", genre: "f" },
    { nom: "salle du trône", genre: "f" },
    { nom: "place publique", genre: "f" },
    { nom: "sénat", genre: "m" },
    { nom: "atelier d’imprimerie de Gutenberg", genre: "m" },
    { nom: "galère", genre: "f" },
    { nom: "cabinet d’alchimie", genre: "m" },
    { nom: "Attentat Kennedy", genre: "m" },
    { nom: "galerie des glaces", genre: "f" },
    { nom: "jardin botanique", genre: "m" },
    { nom: "bastille", genre: "f" },
    { nom: "Titanic", genre: "m" },
    { nom: "salon des philosophes", genre: "m" },
    { nom: "Temple maya", genre: "m" },
    { nom: "laboratoire de physique", genre: "m" },
    { nom: "écuries royales", genre: "f" },
    { nom: "hameau de la reine", genre: "m" },
    { nom: "cabinet des curiosités", genre: "m" },
    { nom: "chapelle ardente", genre: "f" }
  ]
};

export { lieuxParEpoque };
