// SRC/JS/mobiles.js

export const mobiles = {
  medieval: [
    "Venger l’honneur de votre famille bafoué par la victime.",
    "Prendre la place de la victime à la cour.",
    "Empêcher la victime de révéler votre secret d’hérésie.",
    "Récupérer un héritage injustement détenu par la victime.",
    "Faire payer une humiliation subie lors d’un tournoi.",
    "Mettre fin à un chantage de la victime.",
    "Rivalité amoureuse pour la main d’une dame/seigneur.",
    "Protéger votre clan d’une dénonciation de la victime.",
    "Obtenir vengeance pour un parent exécuté sur ordre de la victime.",
    "Récupérer vos terres spoliées par la victime.",
    "Éviter d’être accusé(e) à tort par la victime.",
    "Mettre fin à des dettes écrasantes envers la victime.",
    "Empêcher la victime de révéler une trahison passée.",
    "Venger une trahison politique.",
    "Prendre le contrôle du fief.",
    "Faire disparaître un rival pour la succession.",
    "Punir la victime pour avoir rompu une promesse de mariage.",
    "Effacer une dette de sang.",
    "Protéger un enfant illégitime caché.",
    "Mettre fin à un harcèlement ou des menaces.",
    "Refuser un mariage imposé par la victime.",
    "Se venger d’une dénonciation pour sorcellerie.",
    "Mettre fin à une rivalité de pouvoir.",
    "Masquer votre implication dans un complot.",
    "Éviter que votre secret (bâtardise, vol…) ne soit révélé.",
    "Venger un affront public reçu à la taverne.",
    "Empêcher la victime de s’emparer du domaine.",
    "Éviter d’être déshonoré(e) par la victime.",
    "Empêcher la perte de votre statut de prévôt.",
    "Faire taire la victime qui vous faisait chanter.",
    "Effacer la honte d’avoir été battu(e) par la victime.",
    "Protéger un(e) proche menacé(e) par la victime.",
    "Se venger d’avoir été banni(e) à cause de la victime.",
    "Empêcher la divulgation d’un secret de famille.",
    "Récupérer des biens volés par la victime.",
    "Punir la victime pour avoir détruit votre famille.",
    "Empêcher la victime de vous priver de votre héritage.",
    "Mettre fin à une injustice subie par votre lignée.",
    "Agir sous la pression d’un maître manipulateur.",
    "Rivalité pour un titre de noblesse ou de chevalier."
  ],
  renaissance: [
    "Rivalité artistique avec la victime.",
    "Empêcher la victime de voler votre invention.",
    "Venger une trahison amoureuse.",
    "Concurrence pour une commande royale.",
    "Punir la victime pour avoir détruit votre réputation.",
    "Mettre fin à un chantage sur un secret d’état.",
    "Obtenir un poste convoité à la cour.",
    "Empêcher la victime de vous discréditer auprès du duc.",
    "Venger l’exil de votre famille imposé par la victime.",
    "Empêcher la révélation d’un faux monnayage.",
    "Prendre la place de la victime comme favori(te) du prince.",
    "Obtenir vengeance pour un amour éconduit.",
    "Rivalité pour la protection d’un mécène.",
    "Mettre fin à un procès qui risquait de vous ruiner.",
    "Empêcher la victime de dénoncer votre hérésie.",
    "Préserver votre honneur sali publiquement.",
    "Se venger d’une dénonciation à l’Inquisition.",
    "Protéger votre famille d’un scandale.",
    "Empêcher la victime de voler un brevet.",
    "Rivalité pour l’accès à la bibliothèque privée du duc.",
    "Montrer votre supériorité intellectuelle.",
    "Empêcher la victime de révéler votre origine illégitime.",
    "Venger une humiliation subie lors d’un bal.",
    "Prendre le contrôle d’un atelier ou d’un commerce.",
    "Mettre fin à une dette écrasante.",
    "Rivalité pour l’amour d’un(e) noble.",
    "Empêcher la victime d’usurper votre identité.",
    "Venger la ruine de votre famille.",
    "Punir la victime pour avoir trahi une société secrète.",
    "Empêcher la victime de révéler des lettres compromettantes.",
    "Protéger un(e) proche menacé(e) de prison.",
    "Obtenir un privilège commercial.",
    "Faire taire la victime qui menaçait votre liberté.",
    "Effacer un affront subi lors d’une représentation.",
    "Empêcher un mariage arrangé par la victime.",
    "Venger la perte d’une œuvre d’art.",
    "S’assurer de l’héritage d’un mécène.",
    "Faire payer à la victime la perte de votre atelier.",
    "Empêcher la publication d’un pamphlet contre vous.",
    "Venger la perte de votre honneur académique."
  ],
  victorien: [
    "Empêcher la victime de révéler un scandale familial.",
    "Venger une humiliation publique lors d’un bal.",
    "Prendre la place de la victime dans un testament.",
    "Empêcher la ruine de votre réputation par la victime.",
    "Mettre fin à un chantage concernant un secret intime.",
    "Rivalité pour une promotion dans la société.",
    "Empêcher la victime de dévoiler votre dette.",
    "Venger un amour perdu à cause de la victime.",
    "Concurrence dans le monde scientifique.",
    "Empêcher la victime de révéler une fraude.",
    "Se venger d’avoir été écarté(e) d’un bal mondain.",
    "Prendre la direction d’une société.",
    "Venger un héritage volé.",
    "Mettre fin à des avances indésirables.",
    "Préserver un secret médical.",
    "Empêcher la victime de révéler votre double vie.",
    "Rivalité littéraire ou artistique.",
    "Venger la ruine d’un proche.",
    "Empêcher la victime de vous faire licencier.",
    "Venger la perte d’un poste prestigieux.",
    "Protéger votre famille d’un scandale.",
    "Empêcher la divulgation d’une liaison illicite.",
    "Punir la victime pour avoir détruit votre invention.",
    "Se venger d’une dénonciation à la police.",
    "Concurrence pour un héritage.",
    "Empêcher la victime d’accéder à la haute société.",
    "Venger une trahison amicale.",
    "Mettre fin à un harcèlement.",
    "Empêcher la victime de prendre le contrôle d’une entreprise.",
    "Rivalité dans le club le plus select de la ville.",
    "Venger la perte d’un(e) fiancé(e).",
    "Empêcher la révélation d’une adoption secrète.",
    "Mettre fin à un contrat ruineux.",
    "Rivalité sur une découverte scientifique.",
    "Empêcher la victime de révéler votre passé criminel.",
    "Obtenir la garde d’un enfant.",
    "Venger un vol de bijoux.",
    "Mettre fin à un harcèlement moral.",
    "Punir la victime pour avoir sali votre nom.",
    "Empêcher la victime de vous ruiner aux jeux."
  ],
  western: [
    "Venger un vol de bétail attribué à la victime.",
    "Empêcher la victime de témoigner contre vous au procès.",
    "Rivalité pour la propriété d’une terre.",
    "Prendre la place de la victime au saloon.",
    "Faire payer la victime pour avoir volé votre cheval.",
    "Mettre fin à un chantage pour un braquage passé.",
    "Venger une humiliation lors d’un duel.",
    "Empêcher la victime de révéler votre passé criminel.",
    "Obtenir la main d’une personne convoitée.",
    "Rivalité pour le contrôle de la mine d’or.",
    "Empêcher la victime de ruiner votre commerce.",
    "Venger la perte d’un(e) proche lors d’une fusillade.",
    "Prendre la tête d’une bande de hors-la-loi.",
    "Mettre fin à une dette écrasante au poker.",
    "Empêcher la victime de vendre votre ranch.",
    "Venger la perte de votre emploi à cause de la victime.",
    "Obtenir le poste de shérif.",
    "Empêcher la victime de révéler un secret de famille.",
    "Punir la victime pour avoir incendié vos récoltes.",
    "Rivalité pour le titre de meilleur tireur.",
    "Se venger d’avoir été banni(e) du saloon.",
    "Empêcher la victime de révéler votre implication dans un braquage.",
    "Venger la perte d’un partenaire de jeu.",
    "Mettre fin à un harcèlement au saloon.",
    "Rivalité pour l’amour d’une serveuse.",
    "Empêcher la victime de vous faire arrêter.",
    "Venger la trahison d’un ancien complice.",
    "Punir la victime pour avoir volé votre or.",
    "Empêcher la vente de votre propriété.",
    "Venger la perte de votre réputation.",
    "Obtenir la récompense promise pour la capture de la victime.",
    "Mettre fin à un racket.",
    "Rivalité pour le poste de maire.",
    "Empêcher la victime de révéler un faux testament.",
    "Venger l’incendie de votre grange.",
    "Mettre fin à un harcèlement sur votre famille.",
    "Rivalité pour la construction du chemin de fer.",
    "Punir la victime pour avoir détruit votre commerce.",
    "Empêcher la victime de révéler votre double vie.",
    "Venger la perte de votre bétail."
  ],
  contemporain: [
    "Empêcher la victime de révéler un secret professionnel.",
    "Venger une trahison amoureuse.",
    "Obtenir une promotion convoitée.",
    "Empêcher la victime de vous faire licencier.",
    "Mettre fin à un harcèlement au travail.",
    "Rivalité pour la direction d’un projet.",
    "Faire payer la victime pour une dénonciation mensongère.",
    "Empêcher la victime de ruiner votre réputation sur les réseaux.",
    "Venger un licenciement injuste.",
    "Prendre la place de la victime dans une start-up.",
    "Empêcher la victime de révéler une fraude.",
    "Venger la publication d’une rumeur.",
    "Obtenir la garde d’un enfant.",
    "Mettre fin à une dette écrasante.",
    "Rivalité pour un héritage.",
    "Empêcher la victime de publier un article compromettant.",
    "Venger un vol d’idée.",
    "Prendre la tête d’une association.",
    "Empêcher la victime de révéler votre double vie.",
    "Venger la perte d’un(e) ami(e) à cause de la victime.",
    "Mettre fin à un chantage.",
    "Rivalité pour une place en équipe.",
    "Empêcher la victime de saboter votre projet.",
    "Venger la perte d’un emploi.",
    "Rivalité sur une récompense professionnelle.",
    "Empêcher la diffusion d’une vidéo compromettante.",
    "Venger une humiliation publique.",
    "Prendre la place de la victime dans un concours.",
    "Empêcher la victime de révéler votre passé judiciaire.",
    "Faire taire un lanceur d’alerte.",
    "Venger la perte d’un contrat important.",
    "Empêcher la victime de ruiner votre mariage.",
    "Rivalité pour une clientèle prestigieuse.",
    "Obtenir la reconnaissance d’une invention.",
    "Venger l’échec d’une entreprise commune.",
    "Mettre fin à une campagne de dénigrement.",
    "Empêcher la victime de révéler une liaison.",
    "Venger la perte d’un ami d’enfance.",
    "Rivalité pour un appartement convoité.",
    "Empêcher la victime de détruire votre famille."
  ],
  futuriste: [
    "Empêcher la victime de pirater votre mémoire.",
    "Venger la perte d’un rang dans la station orbitale.",
    "Obtenir le commandement du vaisseau.",
    "Empêcher la victime de révéler un secret génétique.",
    "Mettre fin à un chantage sur vos origines.",
    "Rivalité pour l’accès à une technologie secrète.",
    "Venger un sabotage de votre module.",
    "Prendre la place de la victime dans le conseil scientifique.",
    "Empêcher la victime de détruire votre avatar numérique.",
    "Venger la modification de votre code ADN.",
    "Mettre fin à une dette énergétique écrasante.",
    "Rivalité pour une mission interstellaire.",
    "Empêcher la victime de révéler votre double identité.",
    "Venger la perte d’un compagnon androïde.",
    "Obtenir le brevet d’une invention révolutionnaire.",
    "Empêcher la victime de vous exiler sur une planète lointaine.",
    "Venger un hack de vos souvenirs.",
    "Mettre fin à un harcèlement cybernétique.",
    "Rivalité pour le poste de chef de station.",
    "Empêcher la victime de saboter votre mission.",
    "Venger la perte d’un proche lors d’une expérience.",
    "Prendre la direction d’une recherche majeure.",
    "Empêcher la victime de révéler votre implication dans une rébellion.",
    "Venger la destruction de votre laboratoire.",
    "Mettre fin à une menace d’effacement mémoire.",
    "Rivalité pour l’accès à l’IA centrale.",
    "Empêcher la victime de révéler un trafic de nano-robots.",
    "Venger la perte d’un projet de colonisation.",
    "Obtenir une place sur le prochain vaisseau.",
    "Empêcher la victime de vous faire passer pour un traître.",
    "Venger une tentative d’assassinat robotique.",
    "Mettre fin à un racket énergétique.",
    "Rivalité pour l’accès aux données secrètes.",
    "Empêcher la révélation d’un clonage illégal.",
    "Venger la perte d’une intelligence artificielle.",
    "Prendre la place de la victime sur le projet Alpha.",
    "Empêcher la victime de saboter le réseau.",
    "Venger la perte d’un partenaire d’expédition.",
    "Mettre fin à une manipulation de votre ADN.",
    "Obtenir le leadership d’une colonie spatiale."
  ],
  historique: [
    "Venger une trahison politique.",
    "Empêcher la victime de révéler un secret d’état.",
    "Prendre la place de la victime dans la succession.",
    "Mettre fin à une dénonciation pour espionnage.",
    "Rivalité pour obtenir les faveurs du monarque.",
    "Venger l’exil de votre famille.",
    "Empêcher la victime de révéler un adultère.",
    "Obtenir une charge à la cour.",
    "Venger une humiliation publique.",
    "Mettre fin à un pamphlet compromettant.",
    "Protéger un(e) proche d’une arrestation.",
    "Empêcher la victime de ruiner votre réputation.",
    "Venger la perte d’un héritage.",
    "Prendre la tête d’une académie ou institution.",
    "Empêcher la révélation d’un secret scientifique.",
    "Venger une exclusion d’un salon ou club.",
    "Obtenir la protection d’un puissant.",
    "Empêcher la victime de vous discréditer auprès du roi.",
    "Rivalité pour la direction d’une expédition.",
    "Venger la perte d’une invention ou découverte.",
    "Mettre fin à un procès en sorcellerie.",
    "Empêcher la publication de lettres ou mémoires.",
    "Venger une accusation injuste.",
    "Prendre la place de la victime dans une société secrète.",
    "Empêcher la victime de dénoncer une conspiration.",
    "Venger la perte d’un(e) ami(e) d’enfance.",
    "Mettre fin à un duel de réputation.",
    "Rivalité pour la direction d’une troupe de théâtre.",
    "Empêcher la victime de saboter un traité diplomatique.",
    "Venger une révélation sur vos origines.",
    "Obtenir une pension royale.",
    "Empêcher la victime de vous accuser de vol.",
    "Venger la perte d’un tableau ou manuscrit.",
    "Mettre fin à une campagne de calomnie.",
    "Rivalité pour le titre de scientifique du roi.",
    "Empêcher la victime de révéler des codes secrets.",
    "Venger la perte d’un poste d’ambassadeur.",
    "Mettre fin à une menace d’exil.",
    "Rivalité pour la publication d’un ouvrage.",
    "Empêcher la victime de faire exécuter un(e) proche."
  ]
};
