// Ajoute cette fonction tout en haut du fichier
function imageAleatoire() {
  const n = Math.floor(Math.random() * 15) + 1; // 1 à 15 inclus
  return `Public/images/personnage${n}.png`;
}

// SRC/JS/personnages.js

const personnagesParEpoque = {
medieval: [
  { nom: "Ysabeau la Servante", image: "Public/images/personnage1.png", role: "Servante fidèle", description: "Toujours à l’écoute des ragots.", categories: ["suspect","victime","temoin"] },
  { nom: "Gaspard le Chevalier", image: "Public/images/personnage1.png", role: "Chevalier loyal", description: "Redouté sur le champ de bataille.", categories: ["suspect","victime","temoin"] },
  { nom: "Aliénor la Dame", image: "Public/images/personnage1.png", role: "Dame mystérieuse", description: "Son regard cache de nombreux secrets.", categories: ["suspect","victime","temoin"] },
  { nom: "Arthus le Bouffon", image: "Public/images/personnage1.png", role: "Bouffon malicieux", description: "Ses plaisanteries cachent parfois de sombres vérités.", categories: ["suspect","victime","temoin"] },
  { nom: "Enguerrand le Moine", image: "Public/images/personnage1.png", role: "Moine austère", description: "Confident de tous.", categories: ["suspect","victime","temoin"] },
  { nom: "Berthe la Cuisinière", image: "Public/images/personnage1.png", role: "Cuisinière généreuse", description: "Sa cuisine rassemble tout le château.", categories: ["suspect","victime","temoin"] },
  { nom: "Mahaut la Lavandière", image: "Public/images/personnage1.png", role: "Lavandière discrète", description: "Observe sans être vue.", categories: ["suspect","victime","temoin"] },
  { nom: "Colin le Ménestrel", image: "Public/images/personnage1.png", role: "Ménestrel charmeur", description: "Porteur de nouvelles de cour.", categories: ["suspect","victime","temoin"] },
  { nom: "Thomas le Prévôt", image: "Public/images/personnage1.png", role: "Prévôt rigoureux", description: "Garant de la loi.", categories: ["suspect","victime","temoin"] },
  { nom: "Hugues le Forgeron", image: "Public/images/personnage1.png", role: "Forgeron costaud", description: "Discret et fort.", categories: ["suspect","victime","temoin"] },
  { nom: "Rémi le Page", image: "Public/images/personnage1.png", role: "Jeune page", description: "Toujours prêt à rendre service.", categories: ["suspect","victime","temoin"] },
  { nom: "Béatrix la Guérisseuse", image: "Public/images/personnage1.png", role: "Guérisseuse", description: "Maitresse des plantes.", categories: ["suspect","victime","temoin"] },
  { nom: "Lambert le Cuisinier", image: "Public/images/personnage1.png", role: "Cuisinier adroit", description: "Sait tout ce qui passe en cuisine.", categories: ["suspect","victime","temoin"] },
  { nom: "Isabeau la Tisseuse", image: "Public/images/personnage1.png", role: "Tisseuse habile", description: "Ses doigts agiles cachent de lourds secrets.", categories: ["suspect","victime","temoin"] },
  { nom: "Renaud l'Archer", image: "Public/images/personnage1.png", role: "Archer du domaine", description: "Discret lors des complots.", categories: ["suspect","victime","temoin"] },
  { nom: "Jehanne la Dame de compagnie", image: "Public/images/personnage1.png", role: "Dame de compagnie", description: "Accompagne la maîtresse partout.", categories: ["suspect","victime","temoin"] },
  { nom: "Guillaume le Châtelain", image: "Public/images/personnage1.png", role: "Châtelain", description: "Seigneur du château, respecté.", categories: ["suspect","victime","temoin"] },
  { nom: "Eudes le Prêtre", image: "Public/images/personnage1.png", role: "Prêtre", description: "Confesse tout le village.", categories: ["suspect","victime","temoin"] },
  { nom: "Guillemette la Bâtarde", image: "Public/images/personnage1.png", role: "Enfant illégitime", description: "Cherche à s’intégrer.", categories: ["suspect","victime","temoin"] },
  { nom: "Etienne le Sénéchal", image: "Public/images/personnage1.png", role: "Sénéchal", description: "Gère les comptes et querelles.", categories: ["suspect","victime","temoin"] },
  { nom: "Gaudry le Sergent", image: "Public/images/personnage1.png", role: "Sergent d’armes", description: "Veille sur la sécurité.", categories: ["suspect","victime","temoin"] },
  { nom: "Marion la Fille du meunier", image: "Public/images/personnage1.png", role: "Fille du meunier", description: "Entend tout près du château.", categories: ["suspect","victime","temoin"] },
  { nom: "Héloïse la Dame de cœur", image: "Public/images/personnage1.png", role: "Dame de cœur", description: "Ses amours font jaser.", categories: ["suspect","victime","temoin"] },
  { nom: "Aymard le Messager", image: "Public/images/personnage1.png", role: "Messager", description: "Porteur de nouvelles et menaces.", categories: ["suspect","victime","temoin"] },
  { nom: "Baudouin l’Écuyer", image: "Public/images/personnage1.png", role: "Écuyer", description: "Rêve de gloire.", categories: ["suspect","victime","temoin"] },
  { nom: "Perrot le Garde", image: "Public/images/personnage1.png", role: "Garde du château", description: "Pas toujours sobre.", categories: ["suspect","victime","temoin"] },
  { nom: "Adélaïde la Veuve", image: "Public/images/personnage1.png", role: "Veuve éplorée", description: "Mari mort dans des circonstances troubles.", categories: ["suspect","victime","temoin"] },
  { nom: "Gilles le Moissonneur", image: "Public/images/personnage1.png", role: "Moissonneur", description: "S’invite souvent en cuisine.", categories: ["suspect","victime","temoin"] },
  { nom: "Isambart le Charpentier", image: "Public/images/personnage1.png", role: "Charpentier", description: "Entend tout ce qui grince.", categories: ["suspect","victime","temoin"] },
  { nom: "Odeline la Sage-femme", image: "Public/images/personnage1.png", role: "Sage-femme", description: "Secrets des naissances.", categories: ["suspect","victime","temoin"] },
  { nom: "Agnès la Boulangère", image: "Public/images/personnage1.png", role: "Boulangère", description: "Fournit pain et rumeurs.", categories: ["suspect","victime","temoin"] },
  { nom: "Barthélemy le Berger", image: "Public/images/personnage1.png", role: "Berger", description: "Observe tout près des murs.", categories: ["suspect","victime","temoin"] },
  { nom: "Roseline la Jardinière", image: "Public/images/personnage1.png", role: "Jardinière", description: "Cultive les confidences.", categories: ["suspect","victime","temoin"] },
  { nom: "Thibaut le Tonnelier", image: "Public/images/personnage1.png", role: "Tonnelier", description: "Goûte parfois trop le vin.", categories: ["suspect","victime","temoin"] },
  { nom: "Perrine la Couturière", image: "Public/images/personnage1.png", role: "Couturière", description: "Écoute beaucoup.", categories: ["suspect","victime","temoin"] },
  { nom: "Raimond le Jongleur", image: "Public/images/personnage1.png", role: "Jongleur", description: "Anime les soirées, fouille les poches.", categories: ["suspect","victime","temoin"] },
  { nom: "Marguerite la Nonne", image: "Public/images/personnage1.png", role: "Nonne pieuse", description: "Sa piété est sans faille.", categories: ["suspect","victime","temoin"] },
  { nom: "Hervé le Maître d’armes", image: "Public/images/personnage1.png", role: "Maître d’armes", description: "Forme les jeunes nobles.", categories: ["suspect","victime","temoin"] },
  { nom: "Guibert le Voleur repenti", image: "Public/images/personnage1.png", role: "Voleur repenti", description: "Cherche à se racheter.", categories: ["suspect","victime","temoin"] },
  { nom: "Alix la Fille du forgeron", image: "Public/images/personnage1.png", role: "Fille du forgeron", description: "Aide son père et rêve de liberté.", categories: ["suspect","victime","temoin"] },
  { nom: "Blaise le Tavernier", image: "Public/images/personnage1.png", role: "Tavernier du village", description: "Il sert à boire et des rumeurs.", categories: ["suspect","victime","temoin"] }
],
 renaissance: [
  { nom: "Leonardo l’Inventeur", image: "Public/images/personnage1.png", role: "Génie créatif", description: "Plongé dans ses croquis.", categories: ["suspect","victime","temoin"] },
  { nom: "Giulietta la Dame de compagnie", image: "Public/images/personnage1.png", role: "Confidente avisée", description: "Connait chaque secret du palais.", categories: ["suspect","victime","temoin"] },
  { nom: "Donatello le Sculpteur", image: "Public/images/personnage1.png", role: "Sculpteur talentueux", description: "Ses œuvres cachent parfois des messages.", categories: ["suspect","victime","temoin"] },
  { nom: "Isabella la Duchesse", image: "Public/images/personnage1.png", role: "Duchesse raffinée", description: "Son influence s’étend dans le duché.", categories: ["suspect","victime","temoin"] },
  { nom: "Francesco le Banquier", image: "Public/images/personnage1.png", role: "Banquier influent", description: "Ses finances lui valent des ennemis.", categories: ["suspect","victime","temoin"] },
  { nom: "Raffaella la Courtisane", image: "Public/images/personnage1.png", role: "Courtisane en vue", description: "Ses charmes font tourner les têtes.", categories: ["suspect","victime","temoin"] },
  { nom: "Bartolomeo le Condottiere", image: "Public/images/personnage1.png", role: "Mercenaire redouté", description: "Vend ses services au plus offrant.", categories: ["suspect","victime","temoin"] },
  { nom: "Lucrezia la Peintre", image: "Public/images/personnage1.png", role: "Peintre passionnée", description: "Immortalise les secrets de la noblesse.", categories: ["suspect","victime","temoin"] },
  { nom: "Giovanni le Cardinal", image: "Public/images/personnage1.png", role: "Prince de l’Église", description: "Tire les ficelles dans l’ombre.", categories: ["suspect","victime","temoin"] },
  { nom: "Fiorenzo le Musicien", image: "Public/images/personnage1.png", role: "Musicien virtuose", description: "Sa musique charme et manipule.", categories: ["suspect","victime","temoin"] },
  { nom: "Caterina la Médium", image: "Public/images/personnage1.png", role: "Mystique énigmatique", description: "Prétend voir l’avenir.", categories: ["suspect","victime","temoin"] },
  { nom: "Lorenzo le Marchand", image: "Public/images/personnage1.png", role: "Marchand prospère", description: "Contrôle de nombreux échanges commerciaux.", categories: ["suspect","victime","temoin"] },
  { nom: "Camilla la Tisseuse", image: "Public/images/personnage1.png", role: "Tisseuse habile", description: "Ses tissus sont prisés en ville.", categories: ["suspect","victime","temoin"] },
  { nom: "Vittorio le Médecin", image: "Public/images/personnage1.png", role: "Médecin renommé", description: "Soigne les puissants, ou les empoisonne ?", categories: ["suspect","victime","temoin"] },
  { nom: "Beatrice la Gouvernante", image: "Public/images/personnage1.png", role: "Gouvernante stricte", description: "Surveille les jeunes nobles.", categories: ["suspect","victime","temoin"] },
  { nom: "Orlando le Poète", image: "Public/images/personnage1.png", role: "Poète rêveur", description: "Ses vers révèlent parfois des secrets.", categories: ["suspect","victime","temoin"] },
  { nom: "Maddalena la Jardinière", image: "Public/images/personnage1.png", role: "Jardinière", description: "Cultive les plantes et les secrets.", categories: ["suspect","victime","temoin"] },
  { nom: "Giulia la Danseuse", image: "Public/images/personnage1.png", role: "Danseuse gracieuse", description: "Présente illumine les bals.", categories: ["suspect","victime","temoin"] },
  { nom: "Salvatore l’Érudit", image: "Public/images/personnage1.png", role: "Érudit respecté", description: "Sagesse recherchée et crainte.", categories: ["suspect","victime","temoin"] },
  { nom: "Rosalba la Couturière", image: "Public/images/personnage1.png", role: "Couturière fine", description: "Habille la noblesse et écoute.", categories: ["suspect","victime","temoin"] },
  { nom: "Luca le Valet", image: "Public/images/personnage1.png", role: "Valet discret", description: "Observe tout, dit peu.", categories: ["suspect","victime","temoin"] },
  { nom: "Costanza la Sage-femme", image: "Public/images/personnage1.png", role: "Sage-femme", description: "Veille aux naissances et secrets de famille.", categories: ["suspect","victime","temoin"] },
  { nom: "Tommaso le Libraire", image: "Public/images/personnage1.png", role: "Libraire", description: "Sait où trouver chaque ragot.", categories: ["suspect","victime","temoin"] },
  { nom: "Pietro le Jardinier", image: "Public/images/personnage1.png", role: "Jardinier", description: "Passionné par les plantes.", categories: ["suspect","victime","temoin"] },
  { nom: "Anastasia la Voleuse", image: "Public/images/personnage1.png", role: "Voleuse", description: "Dérobe cœurs et bijoux.", categories: ["suspect","victime","temoin"] },
  { nom: "Giuseppe le Maître d’hôtel", image: "Public/images/personnage1.png", role: "Maître d’hôtel", description: "Veille aux banquets.", categories: ["suspect","victime","temoin"] },
  { nom: "Alessandro le Jongleur", image: "Public/images/personnage1.png", role: "Jongleur", description: "Amuse la cour, fouille les poches.", categories: ["suspect","victime","temoin"] },
  { nom: "Violetta la Fille du boulanger", image: "Public/images/personnage1.png", role: "Fille du boulanger", description: "Sait tout ce qui se passe.", categories: ["suspect","victime","temoin"] },
  { nom: "Emilia la Veuve", image: "Public/images/personnage1.png", role: "Veuve éplorée", description: "Mari mort mystérieusement.", categories: ["suspect","victime","temoin"] },
  { nom: "Renato le Peintre", image: "Public/images/personnage1.png", role: "Peintre", description: "Immortalise beauté ou trahison.", categories: ["suspect","victime","temoin"] },
  { nom: "Livia la Ménagère", image: "Public/images/personnage1.png", role: "Ménagère", description: "Tient la maison d’une main de fer.", categories: ["suspect","victime","temoin"] },
  { nom: "Domenico le Chef", image: "Public/images/personnage1.png", role: "Chef renommé", description: "Plats délicieux ou dangereux.", categories: ["suspect","victime","temoin"] },
  { nom: "Paola la Lavandière", image: "Public/images/personnage1.png", role: "Lavandière", description: "Connait tous les secrets du linge sale.", categories: ["suspect","victime","temoin"] },
  { nom: "Simone le Garde", image: "Public/images/personnage1.png", role: "Garde du palais", description: "Protège la noblesse.", categories: ["suspect","victime","temoin"] },
  { nom: "Teresa la Fleuriste", image: "Public/images/personnage1.png", role: "Fleuriste", description: "Ses bouquets ornent chaque cérémonie.", categories: ["suspect","victime","temoin"] },
  { nom: "Cesare le Forgeron", image: "Public/images/personnage1.png", role: "Forgeron", description: "Armes réputées dans la région.", categories: ["suspect","victime","temoin"] },
  { nom: "Filippo le Messager", image: "Public/images/personnage1.png", role: "Messager", description: "Livre des lettres… et parfois des menaces.", categories: ["suspect","victime","temoin"] },
  { nom: "Lucia la Dame d’honneur", image: "Public/images/personnage1.png", role: "Dame d’honneur", description: "Toujours près de la duchesse.", categories: ["suspect","victime","temoin"] },
  { nom: "Ruggero le Maître de musique", image: "Public/images/personnage1.png", role: "Maître de musique", description: "Dirige les concerts du palais.", categories: ["suspect","victime","temoin"] },
  { nom: "Marta la Boulangère", image: "Public/images/personnage1.png", role: "Boulangère", description: "Ses pâtisseries sont les meilleures.", categories: ["suspect","victime","temoin"] }
],
  
  victorien: [
  { nom: "Ashford le Comte", image: "Public/images/personnage1.png", role: "Comte influent", description: "Respecté mais parfois craint par ses pairs.", categories:["suspect","victime","temoin"] },
  { nom: "Emily la Gouvernante", image: "Public/images/personnage1.png", role: "Gouvernante stricte", description: "Aucun détail ne lui échappe.", categories:["suspect","victime","temoin"] },
  { nom: "Samuel l’Héritier", image: "Public/images/personnage1.png", role: "Jeune héritier", description: "Ambitieux, il rêve de modernité.", categories:["suspect","victime","temoin"] },
  { nom: "Miss Carter", image: "Public/images/personnage1.png", role: "Vieille demoiselle", description: "Elle observe tout depuis son fauteuil.", categories:["suspect","victime","temoin"] },
  { nom: "Majordome Carter", image: "Public/images/personnage1.png", role: "Majordome", description: "Toujours impeccable, pilier de la maison.", categories:["suspect","victime","temoin"] },
  { nom: "Lady Emily", image: "Public/images/personnage1.png", role: "Lady mondaine", description: "Reine des salons, mène la danse.", categories:["suspect","victime","temoin"] },
  { nom: "Colonel Rutherford", image: "Public/images/personnage1.png", role: "Colonel à la retraite", description: "Son passé militaire intrigue.", categories:["suspect","victime","temoin"] },
  { nom: "Agathe la Cousine", image: "Public/images/personnage1.png", role: "Cousine discrète", description: "S’efface, mais écoute tout.", categories:["suspect","victime","temoin"] },
  { nom: "Dr Finch", image: "Public/images/personnage1.png", role: "Médecin du domaine", description: "Soigne corps et âmes avec tact.", categories:["suspect","victime","temoin"] },
  { nom: "Margery la Pianiste", image: "Public/images/personnage1.png", role: "Pianiste douée", description: "Sa musique enchante les soirées.", categories:["suspect","victime","temoin"] },
  { nom: "Hopkins le Jardinier", image: "Public/images/personnage1.png", role: "Jardinier", description: "Cultive les fleurs et les secrets.", categories:["suspect","victime","temoin"] },
  { nom: "Mrs Doyle la Cuisinière", image: "Public/images/personnage1.png", role: "Cuisinière", description: "Son pudding est célèbre, tout comme ses ragots.", categories:["suspect","victime","temoin"] },
  { nom: "Giles le Palefrenier", image: "Public/images/personnage1.png", role: "Palefrenier", description: "Veille sur les écuries et les chevaux.", categories:["suspect","victime","temoin"] },
  { nom: "Brown le Cocher", image: "Public/images/personnage1.png", role: "Cocher", description: "Connaît tous les trajets et toutes les fuites.", categories:["suspect","victime","temoin"] },
  { nom: "May l’Institutrice", image: "Public/images/personnage1.png", role: "Institutrice", description: "Enseigne aux enfants de la maison.", categories:["suspect","victime","temoin"] },
  { nom: "Violette la Complice", image: "Public/images/personnage1.png", role: "Complice rusée", description: "Toujours prête à semer le doute.", categories:["suspect","victime","temoin"] },
  { nom: "Inspecteur Lavande", image: "Public/images/personnage1.png", role: "Enquêteur perspicace", description: "Résout toutes les énigmes… ou presque.", categories:["suspect","victime","temoin"] },
  { nom: "Madame Célestine", image: "Public/images/personnage1.png", role: "Voyante trouble", description: "Ses visions effraient ou fascinent.", categories:["suspect","victime","temoin"] },
  { nom: "Professeur Grimoire", image: "Public/images/personnage1.png", role: "Scientifique excentrique", description: "Expérimente tout, même l’interdit.", categories:["suspect","victime","temoin"] },
  { nom: "Capitaine Rouge", image: "Public/images/personnage1.png", role: "Marin à la retraite", description: "Raconte de sombres histoires.", categories:["suspect","victime","temoin"] },
  { nom: "Sœur Marguerite", image: "Public/images/personnage1.png", role: "Religieuse silencieuse", description: "Prie pour tous… ou presque.", categories:["suspect","victime","temoin"] },
  { nom: "Docteur Alambic", image: "Public/images/personnage1.png", role: "Médecin mystérieux", description: "Son remède n’est pas toujours sans danger.", categories:["suspect","victime","temoin"] },
  { nom: "Baron Mystère", image: "Public/images/personnage1.png", role: "Noble masqué", description: "Manipule sans jamais se dévoiler.", categories:["suspect","victime","temoin"] },
  { nom: "Comtesse Ombrelune", image: "Public/images/personnage1.png", role: "Aristocrate vénéneuse", description: "Son parfum trouble plus d’un convive.", categories:["suspect","victime","temoin"] },
  { nom: "Victor le Chauffeur", image: "Public/images/personnage1.png", role: "Chauffeur", description: "Écoute tout à travers la vitre.", categories:["suspect","victime","temoin"] },
  { nom: "Jane la Gouvernante adjointe", image: "Public/images/personnage1.png", role: "Gouvernante adjointe", description: "Surveille la maison d’un œil neuf.", categories:["suspect","victime","temoin"] },
  { nom: "Edwin le Valet", image: "Public/images/personnage1.png", role: "Valet de pied", description: "Sert et observe tout le monde.", categories:["suspect","victime","temoin"] },
  { nom: "Daisy la Fleuriste", image: "Public/images/personnage1.png", role: "Fleuriste", description: "Fournit la maison en fleurs et ragots.", categories:["suspect","victime","temoin"] },
  { nom: "Martha la Lingère", image: "Public/images/personnage1.png", role: "Lingère", description: "Lave le linge sale… parfois au sens figuré.", categories:["suspect","victime","temoin"] },
  { nom: "Ernest le Jardinier", image: "Public/images/personnage1.png", role: "Jardinier en chef", description: "Dirige les apprentis, sait tout sur tout.", categories:["suspect","victime","temoin"] },
  { nom: "Nora la Cuisinière", image: "Public/images/personnage1.png", role: "Cuisinière adjointe", description: "Rêve de prendre la place de Mrs Doyle.", categories:["suspect","victime","temoin"] },
  { nom: "Clarence le Dandy", image: "Public/images/personnage1.png", role: "Dandy", description: "Tiré à quatre épingles, se fait remarquer.", categories:["suspect","victime","temoin"] },
  { nom: "Alice la Demoiselle", image: "Public/images/personnage1.png", role: "Jeune demoiselle", description: "Rêve de romance et d’aventure.", categories:["suspect","victime","temoin"] },
  { nom: "Simon l’Écrivain", image: "Public/images/personnage1.png", role: "Écrivain", description: "S’inspire des drames de la maison.", categories:["suspect","victime","temoin"] },
  { nom: "Beatrix la Sage-femme", image: "Public/images/personnage1.png", role: "Sage-femme", description: "Veille sur les naissances et secrets de famille.", categories:["suspect","victime","temoin"] },
  { nom: "George le Facteur", image: "Public/images/personnage1.png", role: "Facteur", description: "Distribue lettres et nouvelles.", categories:["suspect","victime","temoin"] },
  { nom: "Harriet la Couturière", image: "Public/images/personnage1.png", role: "Couturière", description: "Habille toute la maison.", categories:["suspect","victime","temoin"] },
  { nom: "Frederick le Banquier", image: "Public/images/personnage1.png", role: "Banquier", description: "Gère la fortune du domaine.", categories:["suspect","victime","temoin"] },
  { nom: "Laura la Bibliothécaire", image: "Public/images/personnage1.png", role: "Bibliothécaire", description: "Connaît tous les livres et toutes les histoires.", categories:["suspect","victime","temoin"] }
],


 western: [
  { nom: "Billy Boy la gachette facile", image: "Public/images/personnage1.png", role: "Cowboy rapide", description: "Jamais sans son colt, il est redouté en duel.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Sally la Danseuse", image: "Public/images/personnage1.png", role: "Danseuse du saloon", description: "Un sourire pour tous, mais une oreille attentive.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Sheriff Carter", image: "Public/images/personnage1.png", role: "Shérif incorruptible", description: "Il fait régner la loi d’une main de fer.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Doc Brown", image: "Public/images/personnage1.png", role: "Médecin du village", description: "Il soigne les blessures… et les secrets.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Miss Daisy", image: "Public/images/personnage1.png", role: "Maîtresse du saloon", description: "Elle tient son établissement d’une main de fer.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Tommy le Joueur", image: "Public/images/personnage1.png", role: "Joueur professionnel", description: "Il tente toujours sa chance, parfois avec des cartes truquées.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Juanita la Cuisinière", image: "Public/images/personnage1.png", role: "Cuisinière mexicaine", description: "Sa cuisine réchauffe le cœur et la langue.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Red le Bandit", image: "Public/images/personnage1.png", role: "Bandit recherché", description: "Sa tête est mise à prix dans tout l’Ouest.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Sam le Forgeron", image: "Public/images/personnage1.png", role: "Forgeron du bourg", description: "Il répare tout, sauf les cœurs brisés.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Mary la Fermière", image: "Public/images/personnage1.png", role: "Fermière", description: "Elle défend sa terre bec et ongles.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Hank le Barman", image: "Public/images/personnage1.png", role: "Barman", description: "Il mélange les verres et les ragots.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Martha la Couturière", image: "Public/images/personnage1.png", role: "Couturière", description: "Elle recoud les habits… et parfois les plaies.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Jesse le Cowboy", image: "Public/images/personnage1.png", role: "Cow-boy solitaire", description: "Il parcourt les plaines, mystérieux.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Clyde le Fossoyeur", image: "Public/images/personnage1.png", role: "Fossoyeur", description: "Il creuse plus de tombes qu’il n’en dit.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Little Joe", image: "Public/images/personnage1.png", role: "Jeune berger", description: "Il surveille les troupeaux et les disputes.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Rosie la Fleuriste", image: "Public/images/personnage1.png", role: "Fleuriste", description: "Elle vend des fleurs aux vivants et aux morts.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Big Bill", image: "Public/images/personnage1.png", role: "Conducteur de diligence", description: "Il connaît tous les trajets et tous les dangers.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Eli le Pasteur", image: "Public/images/personnage1.png", role: "Pasteur", description: "Il prêche la bonne parole… ou la vengeance.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Bobby l’Indien", image: "Public/images/personnage1.png", role: "Éclaireur indien", description: "Il lit les traces mieux que quiconque.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Clara la Maîtresse d’école", image: "Public/images/personnage1.png", role: "Maîtresse d’école", description: "Elle apprend à lire… ou à mentir.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Slim le Trappeur", image: "Public/images/personnage1.png", role: "Trappeur", description: "Il vit en marge, mais sait tout ce qui se trame.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Duke le Chasseur de primes", image: "Public/images/personnage1.png", role: "Chasseur de primes", description: "Il ne lâche jamais sa proie.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Pearl la Veuve noire", image: "Public/images/personnage1.png", role: "Veuve noire", description: "Ses maris disparaissent mystérieusement.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Dusty le Marchand ambulant", image: "Public/images/personnage1.png", role: "Marchand ambulant", description: "Il vend tout, même des secrets.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Frank le Garçon d’écurie", image: "Public/images/personnage1.png", role: "Garçon d’écurie", description: "Il soigne les chevaux et espionne les voyageurs.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Morgan le Banquier", image: "Public/images/personnage1.png", role: "Banquier", description: "Il gère la fortune de la ville, ou la sienne.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Calamity Jane", image: "Public/images/personnage1.png", role: "Aventurière", description: "Elle n’a peur de rien ni de personne.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Lilly la Sage-femme", image: "Public/images/personnage1.png", role: "Sage-femme", description: "Elle veille sur les naissances et les morts.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Tex le Shérif adjoint", image: "Public/images/personnage1.png", role: "Adjoint du shérif", description: "Toujours prêt à dégainer.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Daisy May la Serveuse", image: "Public/images/personnage1.png", role: "Serveuse du saloon", description: "Elle sert plus d’histoires que de verres.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Jack le Télégraphiste", image: "Public/images/personnage1.png", role: "Télégraphiste", description: "Il transmet les messages… ou les détourne.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Doc Holliday", image: "Public/images/personnage1.png", role: "Dentiste armé", description: "Il soigne ou fait mal, selon le tarif.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Belle la Barmaid", image: "Public/images/personnage1.png", role: "Barmaid", description: "Elle entend et répète tout ce qu’on lui dit.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Pat Garrett", image: "Public/images/personnage1.png", role: "Chasseur de hors-la-loi", description: "Il poursuit les bandits sans relâche.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Preacher", image: "Public/images/personnage1.png", role: "Prédicateur itinérant", description: "Il prêche la morale… ou la terreur.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Buck le Prospecteur", image: "Public/images/personnage1.png", role: "Chercheur d’or", description: "Il rêve de fortune, mais trouve souvent des ennuis.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Maggie la Dentelière", image: "Public/images/personnage1.png", role: "Dentelière", description: "Elle brode les tissus et les histoires.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Slim Jim", image: "Public/images/personnage1.png", role: "Rancher", description: "Il possède de vastes terres et peu d’amis.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Eugene le Photographe", image: "Public/images/personnage1.png", role: "Photographe", description: "Il immortalise les visages, parfois pour la dernière fois.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Goldie la Chercheuse d’or", image: "Public/images/personnage1.png", role: "Chercheuse d’or", description: "Elle trouve toujours une pépite… ou un secret.", categories: ["suspect", "victime", "temoin"] }
],
  
contemporain: [
  { nom: "Lucas le Hacker", image: "Public/images/personnage1.png", role: "Virtuose du clavier", description: "Il accède à tous les secrets numériques.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Emma la Journaliste", image: "Public/images/personnage1.png", role: "Journaliste d’investigation", description: "Rien ne lui échappe, elle cherche la vérité.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Sophie la Cheffe", image: "Public/images/personnage1.png", role: "Cheffe étoilée", description: "Ses plats font le tour du monde.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Antoine le Policier", image: "Public/images/personnage1.png", role: "Policier dévoué", description: "Toujours sur le terrain, il enquête sans relâche.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Inès la Médecin", image: "Public/images/personnage1.png", role: "Médecin généraliste", description: "Elle soigne tout le quartier.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Karim le Chauffeur", image: "Public/images/personnage1.png", role: "Chauffeur VTC", description: "Il connaît tous les coins et potins de la ville.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Mélanie la Prof", image: "Public/images/personnage1.png", role: "Professeure de lycée", description: "Elle motive ses élèves avec passion.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Jules l’Artiste", image: "Public/images/personnage1.png", role: "Artiste urbain", description: "Ses graffitis intriguent la police.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Clara la Startupeuse", image: "Public/images/personnage1.png", role: "Entrepreneuse innovante", description: "Toujours connectée, elle veut changer le monde.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Marc l’Avocat", image: "Public/images/personnage1.png", role: "Avocat redouté", description: "Il gagne tous ses procès.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Amandine la Fleuriste", image: "Public/images/personnage1.png", role: "Fleuriste", description: "Elle connaît la vie de tous ses clients.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Nina la Coach sportive", image: "Public/images/personnage1.png", role: "Coach sportive", description: "Elle motive tout le quartier à bouger.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Victor le Banquier", image: "Public/images/personnage1.png", role: "Banquier", description: "Il gère les finances des plus riches.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Élodie la Babysitter", image: "Public/images/personnage1.png", role: "Babysitter", description: "Elle garde les enfants… et les secrets.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Pierre le Concierge", image: "Public/images/personnage1.png", role: "Concierge", description: "Il voit tout, sait tout, ne dit rien.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Romain le Barman", image: "Public/images/personnage1.png", role: "Barman", description: "Il écoute toutes les confidences nocturnes.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Léa la Blogueuse", image: "Public/images/personnage1.png", role: "Blogueuse influente", description: "Son avis compte sur les réseaux.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Nicolas le Photographe", image: "Public/images/personnage1.png", role: "Photographe", description: "Il immortalise la vie urbaine.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Sarah la Musicienne", image: "Public/images/personnage1.png", role: "Musicienne", description: "Elle joue dans le métro et sur scène.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Kevin le Coach de vie", image: "Public/images/personnage1.png", role: "Coach de vie", description: "Il conseille, parfois trop.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Julie la Libraire", image: "Public/images/personnage1.png", role: "Libraire passionnée", description: "Elle partage ses lectures et ses soupçons.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Dylan le Livreur", image: "Public/images/personnage1.png", role: "Livreur à vélo", description: "Il connaît tous les raccourcis de la ville.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Manon la Chef de projet", image: "Public/images/personnage1.png", role: "Chef de projet", description: "Elle gère tout d’une main de maître.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Camille la Psychologue", image: "Public/images/personnage1.png", role: "Psychologue", description: "Elle écoute tout le quartier.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Alexandre le Comptable", image: "Public/images/personnage1.png", role: "Comptable", description: "Il jongle avec les chiffres et les arrangements.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Marine la Restauratrice", image: "Public/images/personnage1.png", role: "Restauratrice", description: "Elle tient le bistrot du coin.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Paul le DJ", image: "Public/images/personnage1.png", role: "DJ", description: "Il anime toutes les soirées branchées.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Jade la Community Manager", image: "Public/images/personnage1.png", role: "CM", description: "Maîtrise les buzz et les crises en ligne.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Rachid le Gardien", image: "Public/images/personnage1.png", role: "Gardien d’immeuble", description: "Il surveille tout, parfois trop.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Laure la Médiatrice", image: "Public/images/personnage1.png", role: "Médiatrice sociale", description: "Elle calme tous les conflits de voisinage.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Omar le Chauffeur de bus", image: "Public/images/personnage1.png", role: "Chauffeur de bus", description: "Il connaît tous les trajets et les horaires.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Elise la Chef de chantier", image: "Public/images/personnage1.png", role: "Chef de chantier", description: "Elle dirige les ouvriers sans faiblir.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Benoît le Policier municipal", image: "Public/images/personnage1.png", role: "Policier municipal", description: "Il veille à l’ordre sur la place.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Céline la Directrice d’école", image: "Public/images/personnage1.png", role: "Directrice d’école", description: "Elle gère les élèves, les profs et les parents.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Alban le Videur", image: "Public/images/personnage1.png", role: "Videur de boîte", description: "Il trie les clients à l’entrée.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Gabrielle la Sage-femme", image: "Public/images/personnage1.png", role: "Sage-femme", description: "Elle veille sur les naissances du quartier.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Robin le Plombier", image: "Public/images/personnage1.png", role: "Plombier", description: "Il répare tout, mais pas les couples.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Lucie la Graphiste", image: "Public/images/personnage1.png", role: "Graphiste", description: "Elle met de la couleur dans la vie de tous.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Bruno le Chauffagiste", image: "Public/images/personnage1.png", role: "Chauffagiste", description: "Il réchauffe les appartements… et les discussions.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Stéphane le Notaire", image: "Public/images/personnage1.png", role: "Notaire", description: "Il connaît tous les secrets de famille.", categories: ["suspect", "victime", "temoin"] }
],

futuriste: [
  { nom: "Vega la Pilote", image: "Public/images/personnage1.png", role: "Pilote intrépide", description: "Elle manœuvre les vaisseaux les plus rapides.", categories: ["suspect", "victime", "temoin"] },
  { nom: "JAX l’Androïde", image: "Public/images/personnage1.png", role: "Robot multifonction", description: "Il assiste tous les membres d’équipage.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Dr Novak", image: "Public/images/personnage1.png", role: "Scientifique spatial", description: "Il teste de nouvelles technologies.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Zora la Roboticienne", image: "Public/images/personnage1.png", role: "Roboticienne", description: "Elle programme les IA les plus avancées.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Directeur Kwan", image: "Public/images/personnage1.png", role: "Directeur de station", description: "Il dirige la colonie orbitale.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Mia la Technicienne", image: "Public/images/personnage1.png", role: "Technicienne de maintenance", description: "Elle répare tout, même l’inimaginable.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Ikar le Biologiste", image: "Public/images/personnage1.png", role: "Biologiste de l’espace", description: "Il découvre la vie là où on ne l’attend pas.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Chef Rolf", image: "Public/images/personnage1.png", role: "Chef de la sécurité", description: "Il veille à la sécurité de la station.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Tao l’Ingénieur", image: "Public/images/personnage1.png", role: "Ingénieur système", description: "Il anticipe toutes les pannes.", categories: ["suspect", "victime", "temoin"] },
  { nom: "S-19 le Robot", image: "Public/images/personnage1.png", role: "Robot assistant", description: "Il collecte et analyse les données.", categories: ["suspect", "victime", "temoin"] },
  { nom: "EVA l’IA", image: "Public/images/personnage1.png", role: "Intelligence artificielle", description: "Elle orchestre toutes les opérations.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Boris le Technicien", image: "Public/images/personnage1.png", role: "Technicien", description: "Il est responsable de la salle des machines.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Lin la Biologiste", image: "Public/images/personnage1.png", role: "Biologiste", description: "Elle analyse l’ADN extraterrestre.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Yuto le Stagiaire", image: "Public/images/personnage1.png", role: "Stagiaire", description: "Il assiste partout et s’attire des ennuis.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Astra la Navigatrice", image: "Public/images/personnage1.png", role: "Navigatrice", description: "Elle trace les routes spatiales.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Nemo le Prospecteur", image: "Public/images/personnage1.png", role: "Prospecteur de planètes", description: "Il explore les mondes inconnus.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Orion le Commandant", image: "Public/images/personnage1.png", role: "Commandant", description: "Il prend toutes les décisions cruciales.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Nova la Médecin", image: "Public/images/personnage1.png", role: "Médecin spatial", description: "Elle soigne même les blessures exotiques.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Atlas le Transporteur", image: "Public/images/personnage1.png", role: "Conducteur de navette", description: "Il gère les déplacements dans la station.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Pixel le Hacker", image: "Public/images/personnage1.png", role: "Hacker spatial", description: "Il pirate les systèmes ennemis.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Echo la Télépathe", image: "Public/images/personnage1.png", role: "Télépathe", description: "Elle lit les pensées des autres.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Quasar le Cybercriminel", image: "Public/images/personnage1.png", role: "Cybercriminel", description: "Il infiltre les réseaux.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Vortex la Contrebandeuse", image: "Public/images/personnage1.png", role: "Contrebandeuse", description: "Elle fait passer tout ce qui est interdit.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Cosmo l’Agronome", image: "Public/images/personnage1.png", role: "Agronome", description: "Il cultive les plantes dans l’espace.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Stella la Diplomate", image: "Public/images/personnage1.png", role: "Diplomate galactique", description: "Elle négocie avec les autres espèces.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Flash l’Explorateur", image: "Public/images/personnage1.png", role: "Explorateur", description: "Il découvre de nouveaux territoires.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Ion le Physicien", image: "Public/images/personnage1.png", role: "Physicien", description: "Il expérimente des énergies nouvelles.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Xenon la Chimiste", image: "Public/images/personnage1.png", role: "Chimiste", description: "Elle invente de nouveaux composés.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Hyperion le Stratège", image: "Public/images/personnage1.png", role: "Stratège militaire", description: "Il prépare la défense de la station.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Mira la Psychologue", image: "Public/images/personnage1.png", role: "Psychologue", description: "Elle analyse les comportements des équipages.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Zen la Médiatrice", image: "Public/images/personnage1.png", role: "Médiatrice", description: "Elle gère les conflits interstellaires.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Gamma la Pilote de drones", image: "Public/images/personnage1.png", role: "Pilote de drones", description: "Elle surveille la station à distance.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Bolt le Messager", image: "Public/images/personnage1.png", role: "Messager ultra-rapide", description: "Il livre les informations cruciales.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Luna la Botaniste", image: "Public/images/personnage1.png", role: "Botaniste", description: "Elle crée de nouvelles espèces végétales.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Neptune le Plombier spatial", image: "Public/images/personnage1.png", role: "Plombier spatial", description: "Il répare les fuites d’oxygène.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Alpha la Commandante", image: "Public/images/personnage1.png", role: "Commandante", description: "Elle donne les ordres, personne ne conteste.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Delta le Logisticien", image: "Public/images/personnage1.png", role: "Responsable logistique", description: "Il gère les stocks et les flux.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Sigma l’Archiviste", image: "Public/images/personnage1.png", role: "Archiviste", description: "Il conserve toutes les données de la station.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Rhea la Médecin de bord", image: "Public/images/personnage1.png", role: "Médecin de bord", description: "Soigne les bobos gravitationnels.", categories: ["suspect", "victime", "temoin"] }
],
  
historique: [
  { nom: "Cléopâtre", image: "Public/images/personnage1.png", role: "Reine d’Égypte", description: "Sa beauté et son intelligence font trembler les puissants.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Jules César", image: "Public/images/personnage1.png", role: "Empereur romain", description: "Général charismatique, il suscite admiration et complots.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Napoléon Bonaparte", image: "Public/images/personnage1.png", role: "Empereur", description: "Son ambition bouleverse l’Europe.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Marie Curie", image: "Public/images/personnage1.png", role: "Scientifique pionnière", description: "Elle découvre l’invisible.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Alexandre le Grand", image: "Public/images/personnage1.png", role: "Conquérant", description: "Il rêve d’unir le monde.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Jeanne d’Arc", image: "Public/images/personnage1.png", role: "Héroïne", description: "Guidée par ses voix, elle sauve la France.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Louis XIV", image: "Public/images/personnage1.png", role: "Roi Soleil", description: "Il règne en maître sur Versailles.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Mozart", image: "Public/images/personnage1.png", role: "Compositeur", description: "Sa musique séduit toutes les cours.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Victor Hugo", image: "Public/images/personnage1.png", role: "Écrivain engagé", description: "Il défend la justice et la liberté.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Marie-Antoinette", image: "Public/images/personnage1.png", role: "Reine de France", description: "Sa frivolité fait scandale.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Gutenberg", image: "Public/images/personnage1.png", role: "Inventeur", description: "Il révolutionne la diffusion du savoir.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Richelieu", image: "Public/images/personnage1.png", role: "Cardinal", description: "Il manipule la politique dans l’ombre.", categories: ["suspect", "victime", "temoin"] },
  { nom: "George Sand", image: "Public/images/personnage1.png", role: "Femme de lettres", description: "Elle brise les codes de son temps.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Mata Hari", image: "Public/images/personnage1.png", role: "Espionne", description: "Ses charmes cachent de sombres secrets.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Vercingétorix", image: "Public/images/personnage1.png", role: "Chef gaulois", description: "Il résiste à l’envahisseur romain.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Louis Pasteur", image: "Public/images/personnage1.png", role: "Scientifique", description: "Il sauve des vies grâce à ses découvertes.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Émile Zola", image: "Public/images/personnage1.png", role: "Écrivain", description: "Il défend les opprimés par sa plume.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Sarah Bernhardt", image: "Public/images/personnage1.png", role: "Comédienne", description: "La scène n’a pas de secret pour elle.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Charles de Gaulle", image: "Public/images/personnage1.png", role: "Général", description: "Il guide la France en temps de crise.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Honoré de Balzac", image: "Public/images/personnage1.png", role: "Romancier", description: "Il brosse le portrait de la société.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Ramsès II", image: "Public/images/personnage1.png", role: "Pharaon", description: "Son règne marque l’apogée de l’Égypte.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Élisabeth Ire", image: "Public/images/personnage1.png", role: "Reine d’Angleterre", description: "Son règne est celui de la grandeur.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Léonard de Vinci", image: "Public/images/personnage1.png", role: "Génie universel", description: "Il invente, il dessine, il rêve.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Nefertiti", image: "Public/images/personnage1.png", role: "Reine d’Égypte", description: "Sa beauté traverse les siècles.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Benjamin Franklin", image: "Public/images/personnage1.png", role: "Inventeur", description: "Il éclaire le monde de ses idées.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Catherine de Médicis", image: "Public/images/personnage1.png", role: "Reine", description: "Elle intrigue dans l’ombre du pouvoir.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Oscar Wilde", image: "Public/images/personnage1.png", role: "Dandy", description: "Il provoque et fascine la société.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Rosalind Franklin", image: "Public/images/personnage1.png", role: "Biologiste", description: "Elle révèle la structure de la vie.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Galilée", image: "Public/images/personnage1.png", role: "Astronome", description: "Il défie les dogmes par la science.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Molière", image: "Public/images/personnage1.png", role: "Dramaturge", description: "Il fait rire et réfléchir la cour.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Clovis", image: "Public/images/personnage1.png", role: "Roi des Francs", description: "Il fonde une dynastie.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Aliénor d’Aquitaine", image: "Public/images/personnage1.png", role: "Reine", description: "Elle traverse deux royaumes et deux époques.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Henri IV", image: "Public/images/personnage1.png", role: "Roi", description: "Il veut la paix pour tous.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Pierre Curie", image: "Public/images/personnage1.png", role: "Scientifique", description: "Il travaille avec Marie pour percer les mystères de la matière.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Robespierre", image: "Public/images/personnage1.png", role: "Révolutionnaire", description: "Il tranche dans le vif du sujet.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Voltaire", image: "Public/images/personnage1.png", role: "Philosophe", description: "Il défend la tolérance et la raison.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Sophie Germain", image: "Public/images/personnage1.png", role: "Mathématicienne", description: "Elle brille dans un monde d’hommes.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Paul Éluard", image: "Public/images/personnage1.png", role: "Poète", description: "Il chante la liberté et l’amour.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Danton", image: "Public/images/personnage1.png", role: "Tribun", description: "Il harangue la foule dans la Révolution.", categories: ["suspect", "victime", "temoin"] },
  { nom: "Marie de Médicis", image: "Public/images/personnage1.png", role: "Reine", description: "Elle gouverne pour son fils, puis pour elle-même.", categories: ["suspect", "victime", "temoin"] }
],
};

window.personnagesParEpoque = personnagesParEpoque;

// Pour une utilisation en module ES :
// export default personnagesParEpoque;
