// SRC/JS/secrets.js

export const secrets = {
  medieval: [
    "Vous avez volé de la nourriture dans les réserves du château.",
    "Vous entretenez une liaison interdite avec un(e) roturier(ère).",
    "Vous avez falsifié les comptes du seigneur.",
    "Vous priez secrètement selon une autre foi.",
    "Vous avez fait accuser un innocent d’un vol.",
    "Vous avez triché lors d’un tournoi.",
    "Vous avez dissimulé une naissance illégitime.",
    "Vous avez vendu des informations à un clan rival.",
    "Vous avez été banni(e) d’un autre fief.",
    "Vous cachez une ancienne blessure de guerre honteuse.",
    "Vous avez donné de fausses herbes à la guérisseuse.",
    "Vous avez volé un bijou dans la chambre de la victime.",
    "Vous cachez que vous savez lire et écrire.",
    "Vous avez empoisonné un animal du domaine.",
    "Vous avez reçu de l’argent pour mentir à la cour.",
    "Vous vous faites passer pour un(e) autre.",
    "Vous avez eu un enfant caché.",
    "Vous avez trafiqué une lettre de la victime.",
    "Vous avez caché un objet volé dans la chapelle.",
    "Vous avez entendu un secret lors d’une confession.",
    "Vous avez dénoncé un(e) complice de peur d’être découvert(e).",
    "Vous avez été témoin d’un complot contre le seigneur.",
    "Vous connaissez l’identité d’un(e) assassin(e) recherché(e).",
    "Vous avez blessé accidentellement un(e) noble.",
    "Vous cachez votre véritable ascendance.",
    "Vous avez volé des armes dans la forge.",
    "Vous avez menti sur votre âge.",
    "Vous avez remplacé le vin du banquet par de l’eau.",
    "Vous avez copié une lettre secrète.",
    "Vous êtes en fuite depuis un autre royaume.",
    "Vous avez caché une maladie contagieuse.",
    "Vous avez reçu un pot-de-vin d’un marchand.",
    "Vous avez menti au prévôt lors d’une enquête.",
    "Vous avez saboté une charrette.",
    "Vous avez détruit un objet précieux par mégarde.",
    "Vous avez assisté à un rituel interdit.",
    "Vous cachez un amour pour la victime.",
    "Vous avez manipulé le tirage au sort d’un tournoi.",
    "Vous avez trahi un(e) ami(e) d’enfance.",
    "Vous possédez un objet volé à la victime."
  ],
  renaissance: [
    "Vous avez copié l’œuvre d’un(e) autre artiste.",
    "Vous cachez une liaison avec un(e) courtisan(e).",
    "Vous avez volé de l’argent du mécène.",
    "Vous faites partie d’une société secrète.",
    "Vous avez falsifié des documents officiels.",
    "Vous avez révélé un secret d’État à un(e) rival(e).",
    "Vous avez été payé(e) pour discréditer un(e) noble.",
    "Vous êtes le/la parent(e) illégitime d’un(e) héritier(ère).",
    "Vous cachez votre origine roturière.",
    "Vous avez triché lors d’un concours artistique.",
    "Vous avez empoisonné un(e) rival(e) lors d’un banquet.",
    "Vous avez vendu une œuvre volée.",
    "Vous avez fait accuser un(e) innocent(e) de sorcellerie.",
    "Vous cachez une lettre compromettante.",
    "Vous avez détourné des fonds pour une invention.",
    "Vous fréquentez un(e) espion(ne) étranger(ère).",
    "Vous avez aidé un fugitif à s’échapper.",
    "Vous avez fait passer une fausse œuvre pour la vôtre.",
    "Vous avez dissimulé une maladie grave.",
    "Vous cachez une amitié avec un(e) hérétique.",
    "Vous avez écrit des pamphlets anonymes.",
    "Vous avez volé des pigments précieux.",
    "Vous avez saboté une commande royale.",
    "Vous avez menti sur votre identité.",
    "Vous avez falsifié une signature.",
    "Vous avez été exclu(e) d’une académie prestigieuse.",
    "Vous avez trahi un(e) proche pour de l’argent.",
    "Vous avez fait échouer un mariage par jalousie.",
    "Vous cachez un enfant illégitime.",
    "Vous avez menti à l’Inquisition.",
    "Vous avez détruit une œuvre rivale.",
    "Vous avez été surpris(e) en train d’espionner.",
    "Vous avez favorisé la carrière d’un(e) complice.",
    "Vous avez acheté un faux titre nobiliaire.",
    "Vous avez volé des plans d’invention.",
    "Vous avez utilisé de fausses recommandations.",
    "Vous avez fait de la contrebande.",
    "Vous cachez votre participation à un duel interdit.",
    "Vous avez payé un(e) serviteur(se) pour mentir.",
    "Vous avez dérobé un manuscrit précieux."
  ],
  victorien: [
    "Vous cachez une ancienne vie de criminel(le).",
    "Vous avez volé un bijou de famille.",
    "Vous avez falsifié un testament.",
    "Vous entretenez une liaison avec un(e) domestique.",
    "Vous avez triché lors d’une partie de cartes.",
    "Vous avez écrit des lettres anonymes menaçantes.",
    "Vous cachez un parent interné.",
    "Vous avez fait accuser un(e) rival(e) de vol.",
    "Vous avez saboté les résultats d’une expérience scientifique.",
    "Vous cachez une dette de jeu importante.",
    "Vous avez menti sur votre titre de noblesse.",
    "Vous avez fait disparaître un document compromettant.",
    "Vous avez acheté le silence d’un(e) témoin.",
    "Vous fréquentez des cercles interlopes.",
    "Vous avez aidé un(e) criminel(le) à s’échapper.",
    "Vous cachez une maladie honteuse.",
    "Vous avez falsifié des relevés bancaires.",
    "Vous cachez un mariage secret.",
    "Vous avez assisté à une scène compromettante.",
    "Vous avez volé un objet de la collection de la victime.",
    "Vous avez truqué les résultats d’un concours.",
    "Vous avez payé pour un faux alibi.",
    "Vous cachez votre implication dans un scandale mondain.",
    "Vous avez menti sur vos origines.",
    "Vous avez trahi un(e) ami(e) pour de l’argent.",
    "Vous avez été complice d’un vol de bijoux.",
    "Vous avez été surpris(e) dans un club interdit.",
    "Vous avez falsifié une lettre d’amour.",
    "Vous avez été témoin d’une scène de chantage.",
    "Vous avez caché un(e) enfant né(e) hors mariage.",
    "Vous avez détruit une preuve importante.",
    "Vous cachez des visites nocturnes suspectes.",
    "Vous avez volé une invention précieuse.",
    "Vous avez manipulé un(e) domestique pour obtenir des informations.",
    "Vous cachez une double identité.",
    "Vous avez payé un(e) médecin pour un faux certificat.",
    "Vous avez menti à la police lors d’une enquête.",
    "Vous fréquentez les bas-fonds de la ville.",
    "Vous avez imité la signature d’un(e) noble.",
    "Vous avez aidé à cacher un corps."
  ],
  western: [
    "Vous avez braqué une banque dans une autre ville.",
    "Vous cachez un passé de hors-la-loi.",
    "Vous avez triché au poker au saloon.",
    "Vous entretenez une liaison avec la femme d’un autre.",
    "Vous avez volé un cheval.",
    "Vous avez vendu de l’alcool frelaté.",
    "Vous cachez une prime sur votre tête.",
    "Vous avez dénoncé un(e) complice pour éviter la prison.",
    "Vous avez fait disparaître un témoin gênant.",
    "Vous cachez l’or dérobé lors d’un braquage.",
    "Vous avez tué un homme dans un autre État.",
    "Vous avez saboté la diligence.",
    "Vous cachez une blessure reçue lors d’un duel.",
    "Vous avez volé dans la caisse du saloon.",
    "Vous avez aidé un(e) bandit(e) à s’évader.",
    "Vous cachez un enfant naturel.",
    "Vous avez menti au shérif lors d’une enquête.",
    "Vous avez fait accuser un(e) innocent(e).",
    "Vous cachez un butin sous le plancher.",
    "Vous avez vendu des informations à des hors-la-loi.",
    "Vous êtes recherché(e) sous un autre nom.",
    "Vous avez saboté un train.",
    "Vous cachez un lien de parenté avec un(e) criminel(le).",
    "Vous avez volé des armes.",
    "Vous avez trahi votre bande.",
    "Vous cachez la provenance douteuse de votre fortune.",
    "Vous avez attaqué une diligence.",
    "Vous avez payé un(e) témoin pour se taire.",
    "Vous avez détruit une preuve.",
    "Vous cachez une bagarre mortelle.",
    "Vous avez révélé la cachette d’un(e) complice.",
    "Vous avez triché à la loterie du village.",
    "Vous avez empoisonné un puits.",
    "Vous avez vendu un(e) ami(e) aux autorités.",
    "Vous cachez une fausse identité.",
    "Vous avez volé un(e) client(e) dans son sommeil.",
    "Vous avez fabriqué de la fausse monnaie.",
    "Vous avez brûlé une grange pour effacer des preuves.",
    "Vous avez été complice d’un kidnapping.",
    "Vous cachez une tentative de meurtre ratée."
  ],
  contemporain: [
    "Vous avez volé un dossier confidentiel.",
    "Vous cachez une liaison avec un(e) collègue.",
    "Vous avez falsifié des notes ou diplômes.",
    "Vous avez triché lors d’un concours.",
    "Vous avez téléchargé illégalement des fichiers.",
    "Vous cachez une dépendance (jeu, alcool, etc.).",
    "Vous avez menti sur votre CV.",
    "Vous avez fait accuser un(e) collègue à tort.",
    "Vous avez piraté le compte d’un(e) autre.",
    "Vous avez touché des pots-de-vin.",
    "Vous cachez un(e) enfant illégitime.",
    "Vous avez détruit un objet de valeur au bureau.",
    "Vous cachez une altercation avec la victime.",
    "Vous avez menti à votre supérieur(e).",
    "Vous avez payé pour un faux alibi.",
    "Vous avez volé dans la caisse de l’entreprise.",
    "Vous cachez une maladie grave.",
    "Vous avez usurpé l’identité de quelqu’un.",
    "Vous avez harcelé un(e) collègue.",
    "Vous avez caché un(e) proche recherché(e) par la police.",
    "Vous avez triché à un examen.",
    "Vous avez saboté un projet.",
    "Vous cachez un(e) partenaire secret(e).",
    "Vous avez menti lors d’une enquête interne.",
    "Vous avez fait disparaître des preuves numériques.",
    "Vous cachez une double vie.",
    "Vous avez utilisé des fonds publics à des fins personnelles.",
    "Vous avez diffusé une rumeur nuisible.",
    "Vous cachez une liaison passée avec la victime.",
    "Vous avez manipulé des résultats.",
    "Vous avez falsifié votre identité sur les réseaux.",
    "Vous avez été complice d’un détournement.",
    "Vous cachez une plainte déposée contre vous.",
    "Vous avez volé un(e) client(e).",
    "Vous cachez un(e) ami(e) en situation illégale.",
    "Vous avez détourné des emails confidentiels.",
    "Vous cachez une altercation violente.",
    "Vous avez menti pour protéger un(e) complice.",
    "Vous avez payé un(e) hacker pour pirater un compte.",
    "Vous cachez un vol dans un magasin."
  ],
  futuriste: [
    "Vous avez piraté l’IA centrale de la station.",
    "Vous cachez une modification illégale de votre ADN.",
    "Vous avez volé une technologie expérimentale.",
    "Vous avez falsifié votre identité biométrique.",
    "Vous avez eu une liaison avec un(e) androïde.",
    "Vous avez vendu des informations à une mégacorporation.",
    "Vous cachez un(e) clone illégal(e) dans vos quartiers.",
    "Vous avez saboté un module de survie.",
    "Vous avez trafiqué la mémoire d’un(e) collègue.",
    "Vous avez effacé des données compromettantes.",
    "Vous cachez un virus informatique dangereux.",
    "Vous avez modifié le code source d’un(e) robot.",
    "Vous avez menti à l’IA lors d’un interrogatoire.",
    "Vous avez fait passer un(e) passager(ère) clandestin(e).",
    "Vous avez piraté les caméras de surveillance.",
    "Vous cachez un projet illégal de nanotechnologie.",
    "Vous avez falsifié des résultats de recherche.",
    "Vous avez trafiqué un rapport médical.",
    "Vous cachez un trafic de ressources précieuses.",
    "Vous avez saboté un vaisseau concurrent.",
    "Vous avez modifié les souvenirs d’un(e) collègue.",
    "Vous cachez une maladie génétique.",
    "Vous avez effacé les logs d’un incident.",
    "Vous avez fait disparaître un(e) rival(e).",
    "Vous cachez un(e) enfant issu(e) du clonage.",
    "Vous avez triché lors d’une simulation spatiale.",
    "Vous avez vendu des secrets militaires.",
    "Vous cachez un partenariat avec un groupuscule rebelle.",
    "Vous avez piraté le système de navigation.",
    "Vous avez modifié votre apparence grâce à la biotechnologie.",
    "Vous cachez une liaison interdite avec une IA.",
    "Vous avez violé le protocole d’exploration.",
    "Vous avez effacé la mémoire d’un(e) témoin.",
    "Vous cachez une expérience ratée.",
    "Vous avez menti sur votre dossier d’affectation.",
    "Vous avez détourné du matériel de laboratoire.",
    "Vous cachez un(e) espion(ne) parmi l’équipage.",
    "Vous avez saboté le générateur principal.",
    "Vous cachez un accès illégal à la salle des commandes.",
    "Vous avez fait disparaître une intelligence artificielle."
  ],
  historique: [
    "Vous avez trahi votre camp lors d’une guerre.",
    "Vous cachez une liaison avec une figure célèbre.",
    "Vous avez falsifié un document historique.",
    "Vous avez volé un objet au musée royal.",
    "Vous avez aidé un(e) exilé(e) politique.",
    "Vous avez écrit un pamphlet interdit.",
    "Vous cachez une origine étrangère.",
    "Vous avez dénoncé un(e) rival(e) aux autorités.",
    "Vous avez participé à un complot contre le pouvoir.",
    "Vous avez falsifié des résultats scientifiques.",
    "Vous cachez un(e) enfant né(e) hors mariage.",
    "Vous avez volé une invention révolutionnaire.",
    "Vous cachez une dette colossale.",
    "Vous avez participé à une expédition secrète.",
    "Vous avez fait disparaître des lettres compromettantes.",
    "Vous avez menti sur votre rôle dans un événement historique.",
    "Vous avez couvert un(e) criminel(le) célèbre.",
    "Vous avez détourné des fonds de l’État.",
    "Vous cachez une maladie contagieuse.",
    "Vous avez caché un(e) prisonnier(ère) politique.",
    "Vous avez vendu une œuvre d’art volée.",
    "Vous avez espionné pour le compte d’une puissance étrangère.",
    "Vous avez fait accuser un(e) innocent(e) de trahison.",
    "Vous avez détruit un manuscrit précieux.",
    "Vous avez soutenu une cause interdite.",
    "Vous cachez une conversion religieuse.",
    "Vous avez truqué les résultats d’un concours d’académie.",
    "Vous avez manipulé un procès historique.",
    "Vous cachez un faux passeport.",
    "Vous avez écrit sous un pseudonyme interdit.",
    "Vous avez usurpé un titre de noblesse.",
    "Vous avez protégé un(e) hérétique.",
    "Vous avez divulgué des plans militaires.",
    "Vous avez aidé à la fuite d’un(e) condamné(e).",
    "Vous cachez une fortune cachée à l’étranger.",
    "Vous avez falsifié un testament.",
    "Vous avez participé à une révolution secrète.",
    "Vous cachez une invention dangereuse.",
    "Vous avez détourné un convoi royal.",
    "Vous avez couvert un(e) assassin(e) notoire."
  ]
};
